### ISSUE TITLE
企业付款到银行卡总是提示签名错误

### ISSUE THREAD

**Issue by tianxiajiangshan** [binarywang/WxJava#1042]
@班纳睿 你好，企业付款到银行卡的接口获取公钥加密姓名和银行卡号的接口，公钥获取有问题吧

【响应数据】：<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[签名出错，请根据签名算法进行签名]]></return_msg>
<result_code><![CDATA[FAIL]]></result_code>
<err_code><![CDATA[SIGNERROR]]></err_code>
<err_code_des><![CDATA[签名出错，请根据签名算法进行签名]]></err_code_des>
<nonce_str><![CDATA[1557471531874]]></nonce_str>
<mch_id><![CDATA[1525959781]]></mch_id>
<partner_trade_no><![CDATA[1557471507109193068]]></partner_trade_no>
<amount>800</amount>
</xml>

**Comment by tianxiajiangshan** [comment]
com.github.binarywang.wxpay.exception.WxPayException: 返回代码：[SUCCESS]，返回信息：[签名出错，请根据签名算法进行签名]，结果代码：[FAIL]，错误代码：[SIGNERROR]，错误详情：[签名出错，请根据签名算法进行签名]，微信返回的原始报文：
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[签名出错，请根据签名算法进行签名]]></return_msg>
<result_code><![CDATA[FAIL]]></result_code>
<err_code><![CDATA[SIGNERROR]]></err_code>
<err_code_des><![CDATA[签名出错，请根据签名算法进行签名]]></err_code_des>
<nonce_str><![CDATA[1557480542090]]></nonce_str>
<mch_id><![CDATA[1525959781]]></mch_id>
<partner_trade_no><![CDATA[1557480503093407555]]></partner_trade_no>
<amount>720</amount>
</xml>
	at com.github.binarywang.wxpay.exception.WxPayException$Builder.build(WxPayException.java:197)
	at com.github.binarywang.wxpay.exception.WxPayException.from(WxPayException.java:99)
	at com.github.binarywang.wxpay.bean.result.BaseWxPayResult.checkResult(BaseWxPayResult.java:275)
	at com.yaoyao.controller.WxPayController.mcNotifyResult(WxPayController.java:332)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tianxiajiangshan** [comment]
<return_msg><![CDATA[签名出错，请根据签名算法进行签名]]></return_msg>

**Comment by tianxiajiangshan** [comment]
<![CDATA[签名出错，请根据签名算法进行签名]]>

**Comment by tianxiajiangshan** [comment]
签名出错，请根据签名算法进行签名

**Comment by binarywang** [comment]
仔细检查下相关参数
