### ISSUE TITLE
图片上传空指针异常

### ISSUE THREAD

**Issue by nisen6477** [binarywang/WxJava#1092]
### 简要描述
调用 WxMpMaterialServiceImpl 的 mediaImgUpload(File file) 方法时报空指针异常
经过调试，发现问题出在 MediaImgUploadApacheHttpRequestExecutor 的第43行：
httpPost.setHeader("Content-Type", ContentType.MULTIPART_FORM_DATA.toString());

程序执行到这里就抛出异常，异常信息：
java.lang.NullPointerException
	at me.chanjar.weixin.mp.util.requestexecuter.media.MediaImgUploadApacheHttpRequestExecutor.execute(MediaImgUploadApacheHttpRequestExecutor.java:52)
	at me.chanjar.weixin.mp.util.requestexecuter.media.MediaImgUploadApacheHttpRequestExecutor.execute(MediaImgUploadApacheHttpRequestExecutor.java:27)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:323)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)
	at me.chanjar.weixin.mp.api.impl.WxMpMaterialServiceImpl.mediaImgUpload(WxMpMaterialServiceImpl.java:80)

请问这是哪个地方出问题了，上传的文件我已经检查过了，不是空的

### 模块版本情况

* WxJava 模块名:  weixin-java-mp
* WxJava 版本号:  3.3.0

### 期待结果 和 实际情况
期待结果：正常上传到微信，返回图片url
实际情况：空指针异常

是因为我重写了getAccessToken()方法吗，因为我用的第三方平台获取的 authorizedAccessToken，没办法获取到公众号的appSecret，所以这个方法重写成了直接返回 authorizedAccessToken，这里要怎么改?

**Comment by nisen6477** [comment]
找到问题了，是因为没有初始化 WxMpConfigStorage
