### ISSUE TITLE
微信营销接口实现与文档描述不一致

### ISSUE THREAD

**Issue by sinrimin** [binarywang/WxJava#1095]
### 简要描述
MarketingService模块实现与文档描述不一致，`addUserAction` 接口根本无法正常使用

### 模块版本情况

* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 3.4.0

### 期待结果 和 实际情况
[官方文档](https://ad.weixin.qq.com/guide/456)
请求示例中数据格式为
```json
{
    "actions": [
        {
            "user_action_set_id": "<USER_ACTION_SET_ID>",
            "url": "<URL>",
            "action_time": 1513077790,
            "action_type": "COMPLETE_ORDER",
            "trace": {
                "click_id": "<CLICK_ID>"
            },
            "action_param": {
                "value": 40
            }
        }
    ]
}
```
通过API调用后的JSON
```json
[
    {
        "user_action_set_id": "<USER_ACTION_SET_ID>",
        "url": "<URL>",
        "action_time": true,
        "trace": {
            "click_id": "<CLICK_ID>"
        }
    }
]
```
返回结果
```json
{
    "errcode": 900351002,
    "errmsg": "JSON string is malformed."
}
```
原因分析：
1、`action_time` 类型为Unix时间戳Integer型，现在被定义为了Boolean型
2、`action_type` 没有被塞到请求的JSON对象中
3、请求对象最外层是个Json对象，不是数组，对象中的 `actions` 的内容对应这个数组
4、请求头缺少 `application/json`

### 重现步骤
业务代码
```java
       List<WxMpUserAction> wxMpUserActions = Lists.newArrayList();
        WxMpUserAction action = new WxMpUserAction();

        action.setUserActionSetId(sid);
        action.setUrl(url);
        action.setClickId(vid);
        action.setActionType(at);
        action.setActionTime(true);

        wxMpUserActions.add(action);

        service.getMarketingService().addUserAction(wxMpUserActions);
```
结果

### 日志
```log
【请求地址】: https://api.weixin.qq.com/marketing/user_actions/add?version=v1.0&access_token=<ACCESS_TOKEN>
【请求参数】：[{"user_action_set_id":<USER_ACTION_SET_ID>,"url":"<URL>","action_time":true,"trace":{"click_id":"<CLICK_ID>"}}]
【错误信息】：{"errcode":900351002,"errmsg":"JSON string is malformed."}
```
```log
{"errcode":900351002,"errmsg":"JSON string is malformed."}
me.chanjar.weixin.common.error.WxErrorException: {"errcode":900351002,"errmsg":"JSON string is malformed."}
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:325)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:264)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:253)
	at me.chanjar.weixin.mp.api.impl.WxMpMarketingServiceImpl.addUserAction(WxMpMarketingServiceImpl.java:61)
	at com.********.***.*******.endpoint.api.MarketingEndpoint.actions(MarketingEndpoint.java:35)
	at com.********.***.*******.endpoint.api.MarketingEndpoint$$FastClassBySpringCGLIB$$db5c5359.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
Caused by: me.chanjar.weixin.common.error.WxErrorException: {"errcode":900351002,"errmsg":"JSON string is malformed."}
	at me.chanjar.weixin.common.util.http.okhttp.OkHttpSimplePostRequestExecutor.execute(OkHttpSimplePostRequestExecutor.java:38)
	at me.chanjar.weixin.common.util.http.okhttp.OkHttpSimplePostRequestExecutor.execute(OkHttpSimplePostRequestExecutor.java:16)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:304)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:264)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:253)
	at me.chanjar.weixin.mp.api.impl.WxMpMarketingServiceImpl.addUserAction(WxMpMarketingServiceImpl.java:61)
	at com.********.***.*******.endpoint.api.MarketingEndpoint.actions(MarketingEndpoint.java:35)
	at com.********.***.*******.endpoint.api.MarketingEndpoint$$FastClassBySpringCGLIB$$db5c5359.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
```

**Comment by binarywang** [comment]
@007gzs 帮忙看下这个是不是由于微信接口调整导致的？

**Comment by 007gzs** [comment]
action_time 应该是当时写错了，leads_type是新增参数，我改下

**Comment by binarywang** [comment]
@007gzs 什么时间能修复下？

**Comment by binarywang** [comment]
没事，不用了，我来修复

**Comment by binarywang** [comment]
楼主请提供下最新文档地址，
代码里提到的地址：https://wximg.qq.com/wxp/pdftool/get.html?id=rkalQXDBM&pa=39 
貌似是比较老的版本

**Comment by binarywang** [comment]
@007gzs leads_type这个参数没找到，其他部分我准备先修复下了

**Comment by binarywang** [comment]
#1110

**Comment by binarywang** [comment]
3.4.7.B测试版本 已修复，欢迎试用

**Comment by sinrimin** [comment]
抱歉这功能前段时间上线了，现在不敢在生产环境DEBUG，不过 ”请求头缺少 application/json“是肯定会返回错误的，代码里配置的okhttp默认的好像是 "plain/text"，这个请求头不影响公众号的接口请求，但微信广告接口不带的话就直接报错。
