### ISSUE TITLE
微信企业转账到零钱请求对象EntPayRequest  toString方法执行错误

### ISSUE THREAD

**Issue by waterorblue** [binarywang/WxJava#1161]
微信企业转账到零钱请求对象EntPayRequest  toString方法执行错误，错误日志信息如下：

SLF4J: Failed toString() invocation on an object of type [com.github.binarywang.wxpay.bean.entpay.EntPayRequest]
Reported exception:
java.lang.IllegalArgumentException: class com.github.binarywang.wxpay.bean.entpay.EntPayRequest declares multiple JSON fields named mchId
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:170)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.Gson.toJson(Gson.java:661)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)
	at com.github.binarywang.wxpay.bean.entpay.EntPayRequest.toString(EntPayRequest.java:194)

**Comment by waterorblue** [comment]
<dependency>
    <groupId>com.github.binarywang</groupId>
    <artifactId>weixin-java-pay</artifactId>
    <version>3.5.0</version> 
</dependency>

版本3.4.0和3.3.0都有此问题

**Comment by binarywang** [comment]
确实是个问题，由于微信官方字段命名不统一导致的，准备修复一下

**Comment by binarywang** [comment]
3.5.1.B版本已修复，请验证
