### ISSUE TITLE
微信支付下单报错？

### ISSUE THREAD

**Issue by rabbitLove520** [binarywang/WxJava#1289]
### 简要描述
```
Caused by: java.lang.NoSuchMethodError: com.thoughtworks.xstream.XStream.setupDefaultSecurity(Lcom/thoughtworks/xstream/XStream;)V
qiyu_app_1  | 	at me.chanjar.weixin.common.util.xml.XStreamInitializer.getInstance(XStreamInitializer.java:47)
qiyu_app_1  | 	at com.github.binarywang.wxpay.bean.request.BaseWxPayRequest.toXML(BaseWxPayRequest.java:191)
qiyu_app_1  | 	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.unifiedOrder(BaseWxPayServiceImpl.java:353)
qiyu_app_1  | 	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.createOrder(BaseWxPayServiceImpl.java:270)
```

### 模块版本情况
* WxJava 模块名:  weixin-java-pay
* WxJava 版本号:  3.5.0

**Comment by binarywang** [comment]
你自己的xstream版本问题，如果解决不了，自己看下wiki常见问题里相关内容
