### ISSUE TITLE
公众号创建菜单报错了

### ISSUE THREAD

**Issue by hanbin** [binarywang/WxJava#1322]
引用的是：
```
<dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>wx-java-mp-spring-boot-starter</artifactId>
            <version>3.6.0</version>
        </dependency>
```
 创建菜单的时候500错误，是我漏了什么么？

{"timestamp":"Dec 18, 2019 1:31:58 AM","status":500,"error":"Internal Server Error","message":"me.chanjar.weixin.common.util.http.RequestExecutor.execute(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;","path":"/wx/menu/wx0eec88e5b9d9e62d/get"}

**Comment by binarywang** [comment]
500错误是内部错误，要看具体错误信息，你给的信息实在少得可怜

**Comment by hanbin** [comment]
java.lang.NoSuchMethodError: me.chanjar.weixin.common.util.http.RequestExecutor.execute(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:324) ~[weixin-java-mp-3.5.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284) ~[weixin-java-mp-3.5.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.get(BaseWxMpServiceImpl.java:253) ~[weixin-java-mp-3.5.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.get(BaseWxMpServiceImpl.java:258) ~[weixin-java-mp-3.5.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.WxMpMenuServiceImpl.menuGet(WxMpMenuServiceImpl.java:81) ~[weixin-java-mp-3.5.0.jar:na]
	at com.cyzhili.mattress.gzh.controller.WxMenuController.menuGet(WxMenuController.java:124) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.49]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.49]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.49]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:1

**Comment by binarywang** [comment]
很显然是你weixin-java-common版本问题，跟starter的版本不一致导致的
