### ISSUE TITLE
调用 getOAuth2AccessToken 时 返回 Connection pool shut down

### ISSUE THREAD

**Issue by craone** [binarywang/WxJava#1339]
### 简要描述

调用 getOAuth2AccessToken 时 返回 Connection pool shut down

### 模块版本情况
* WxJava 模块名:  weixin-java-mp
* WxJava 版本号: 3.5.0

### 详细描述
微信登录,通过 code 获取用户access token时发生 Connection pool shut down,导致无法后续操作.

自建了一个 `WxMpRedisConfigImpl`继承`WxMpDefaultConfigImpl`
```kotlin
class WxMpRedisConfigImpl(
    private val redisUtils: RedisUtils,
    private val wechatProperties: WechatProperties
) : WxMpDefaultConfigImpl() {
    /**
     * 每个公众号生成独有的存储key.
     */
    override fun getAppId(): String? {
        return wechatProperties.appId
    }

    override fun getSecret(): String? {
        return wechatProperties.secret
    }

    private fun getTicketRedisKey(type: TicketType) = String.format("wx:ticket:key:%s:%s", appId, type.code)

    override fun getAccessToken() = redisUtils[MP_ACCESS_TOKEN_KEY]

    override fun isAccessTokenExpired() = !redisUtils.hasKey(MP_ACCESS_TOKEN_KEY)

    @Synchronized
    override fun updateAccessToken(accessToken: String, expiresInSeconds: Int) {
        redisUtils[(expiresInSeconds - 200).toLong(), MP_ACCESS_TOKEN_KEY] = accessToken
    }

    override fun expireAccessToken() {
        redisUtils.expire(MP_ACCESS_TOKEN_KEY, 0)
    }

    override fun getTicket(type: TicketType) = redisUtils[getTicketRedisKey(type)]

    override fun isTicketExpired(type: TicketType) = redisUtils.getExpire(getTicketRedisKey(type)) < 2

    @Synchronized
    override fun updateTicket(type: TicketType, jsapiTicket: String, expiresInSeconds: Int) {
        redisUtils[(expiresInSeconds - 200).toLong(), getTicketRedisKey(type)] = jsapiTicket
    }

    override fun expireTicket(type: TicketType) {
        redisUtils.expire(getTicketRedisKey(type), 0)
    }

    companion object {
        const val MP_ACCESS_TOKEN_KEY = "mp_****"
    }
}
```

### 日志
```
java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:196)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:268)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at me.chanjar.weixin.common.util.http.apache.ApacheHttpClientSimpleGetRequestExecutor.execute(ApacheHttpClientSimpleGetRequestExecutor.java:39)
	at me.chanjar.weixin.common.util.http.apache.ApacheHttpClientSimpleGetRequestExecutor.execute(ApacheHttpClientSimpleGetRequestExecutor.java:19)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getOAuth2AccessToken(BaseWxMpServiceImpl.java:176)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.oauth2getAccessToken(BaseWxMpServiceImpl.java:187)
	at com.******.service.impl.MemberServiceImpl.fetchWechatUnionIdByCode(MemberServiceImpl.kt:206)
	at com.******.service.impl.MemberServiceImpl$$FastClassBySpringCGLIB$$b6c1d43e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.******.service.impl.MemberServiceImpl$$EnhancerBySpringCGLIB$$5f219855.fetchWechatUnionIdByCode(<generated>)
	at com.******.resolver.Query.wechatUnionIdByCode(Query.kt:265)
	at com.******.resolver.QueryMethodAccess.invoke(Unknown Source)
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:167)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
	at graphql.execution.Execution.executeOperation(Execution.java:161)
	at graphql.execution.Execution.execute(Execution.java:102)
	at graphql.GraphQL.execute(GraphQL.java:605)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:538)
	at graphql.GraphQL.executeAsync(GraphQL.java:502)
	at graphql.servlet.core.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:106)
	at graphql.servlet.core.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:102)
	at graphql.servlet.core.GraphQLQueryInvoker.queryAsync(GraphQLQueryInvoker.java:51)
	at graphql.servlet.core.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:47)
	at graphql.servlet.AbstractGraphQLHttpServlet.query(AbstractGraphQLHttpServlet.java:374)
	at graphql.servlet.AbstractGraphQLHttpServlet.lambda$init$4(AbstractGraphQLHttpServlet.java:237)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:342)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:333)
	at graphql.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:365)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.******.filter.GraphqlAuthTokenFilter.doFilter(GraphqlAuthTokenFilter.kt:20)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by binarywang** [comment]
你这是啥代码？

**Comment by craone** [comment]
大佬是kotlin代码,兼容JAVA的,就是自己写了个 WxMpDefaultConfigImpl, 通过 redis 注入配置,可是为什么请求低层会把请求链接池给关了?我只是简单的调用API请求,其它的请求URL都是通过 spring boot 自带的 WebClient,没有自己引用过 apache http 这个包

**Comment by zenlizc** [comment]
我也遇到同样的问题了，重启服务临时解决的，不知道这个在3.6.0版本解决没有？

**Comment by farawayll** [comment]
我也遇到同样的问题了，重启服务临时解决的，在3.6.0版本解决依然存在

**Comment by farAwayLL** [comment]
因为accesstoken还被nodejs同时使用的原因，因此accesstoken被nodejs存放在数据库。所以我这边的代码是
`@Autowired
	private WxPublicActivityOrderMapper wxPublicActivityOrderMapper;

	@Override
	public String getAccessToken() {
		return wxPublicActivityOrderMapper.selectAccesstoken();
	}

	@Override
	public boolean isAccessTokenExpired() {
		return false;
	}`

**Comment by fengbird** [comment]
我也遇到同样的问题了，重启服务只能临时解决一会儿，过一会儿又会出现这个问题，版本也是3.5.0

**Comment by anand-songs** [comment]
3.6版本还未解决，多线程情况下，存在死循环调用，导致StackOverflowError

**Comment by binarywang** [comment]
> 3.6版本还未解决，多线程情况下，存在死循环调用，导致StackOverflowError

能否提供下具体异常，跟楼主的可能不是同一个问题？建议新开issue，不要在这里回复，谢谢

**Comment by dylanleung** [comment]
我这边使用情况大概是token 失效后还是不停的重试 导致的.

**Comment by binarywang** [comment]
楼上的问题都是同一个问题吗？如果不是，请单独开issue，具体描述下操作过程和相关代码及日志信息

**Comment by binarywang** [comment]
#1523 重复
