### ISSUE TITLE
取消关注公众号事件回调this.aesKey = Base64.decodeBase64(encodingAesKey + "=")报错

### ISSUE THREAD

**Issue by Skqing** [binarywang/WxJava#1379]
### 简要描述
取消关注公众号事件回调报错

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 3.6.1.B

### 详细描述
EncodingAESKey是微信后台随时生成后保存的

取消关注公众号事件回调后在WxMpCryptUtil类的
`this.aesKey = Base64.decodeBase64(encodingAesKey + "=");`
这一行报出的异常

### 日志
```
2020-01-13 14:41:31.637 [http-nio-80-exec-2] ERROR [org.apache.juli.logging.DirectJDKLog.log: 175] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value] with root cause
java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value
	at org.apache.commons.codec.binary.Base64.validateCharacter(Base64.java:798) ~[commons-codec-1.13.jar!/:1.13]
	at org.apache.commons.codec.binary.Base64.decode(Base64.java:477) ~[commons-codec-1.13.jar!/:1.13]
	at org.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:411) ~[commons-codec-1.13.jar!/:1.13]
	at org.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:395) ~[commons-codec-1.13.jar!/:1.13]
	at org.apache.commons.codec.binary.Base64.decodeBase64(Base64.java:694) ~[commons-codec-1.13.jar!/:1.13]
	at me.chanjar.weixin.mp.util.crypto.WxMpCryptUtil.<init>(WxMpCryptUtil.java:42) ~[weixin-java-mp-3.6.1.B.jar!/:?]
	at me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromEncryptedXml(WxMpXmlMessage.java:671) ~[weixin-java-mp-3.6.1.B.jar!/:?]
```

**Comment by Skqing** [comment]
参考：https://developers.weixin.qq.com/community/develop/doc/0002a00b7bcd088eeb89f4d485b000

**Comment by Skqing** [comment]
https://developers.weixin.qq.com/community/develop/doc/000e44168b41c07008c965c7450800

**Comment by binarywang** [comment]
建议楼主直接提交个PR，暂时没有看明白问题，记得做好测试

**Comment by binarywang** [comment]
另外你的问题只是出在取消关注吗？

我在我自己的公众号测试过，使用安全模式，取消关注，没有任何问题。

**Comment by binarywang** [comment]
没有反馈，暂时关闭

**Comment by jiankian** [comment]
common-codec版本只能在1.8 1.9 1.10，升级就没法Base64 decode。用Java自带的MISC包的base64 编码和Java8以上版本自带的base64可以解微信这个编码，但是codec包新版本就不行。郁闷

**Comment by jiankian** [comment]
<dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.14</version> 
        </dependency>
