### ISSUE TITLE
StringUtils.removeFirst()方法找不到---NoSuchMethodError

### ISSUE THREAD

**Issue by goupan1996** [binarywang/WxJava#1380]
### 简要描述
StringUtils.removeFirst()方法找不到---NoSuchMethodError  

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:3.5.0

### 详细描述
当把证书文件放在项目里面时，使用classpath:描述,解析出错
java文件：WxPayConfig.java

      final String prefix = "classpath:";
      String fileHasProblemMsg = "证书文件【" + this.getKeyPath() + "】有问题，请核实！";
      String fileNotFoundMsg = "证书文件【" + this.getKeyPath() + "】不存在，请核实！";
      if (this.getKeyPath().startsWith(prefix)) {
        String path = StringUtils.removeFirst(this.getKeyPath(), prefix);
        if (!path.startsWith("/")) {
          path = "/" + path;
        }

//报错地方，建议替换为replace方法

### 日志

Caused by: java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.removeFirst(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at com.github.binarywang.wxpay.config.WxPayConfig.initSSLContext(WxPayConfig.java:140)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.initSSLContext(WxPayServiceApacheHttpImpl.java:140)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.createHttpClientBuilder(WxPayServiceApacheHttpImpl.java:106)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.post(WxPayServiceApacheHttpImpl.java:70)
	at com.github.binarywang.wxpay.service.impl.EntPayServiceImpl.entPay(EntPayServiceImpl.java:58)
	at com.wenjuanbang.web.WxPayController.userWithDrawal(WxPayController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	... 50 common frames omitted

**Comment by binarywang** [comment]
你这是java基础常见问题，请注意查看wiki里的常见问题

**Comment by goupan1996** [comment]
嗯嗯 自己后面发现这个问题了，把common-lang3包升级了就可以了。谢谢解答！

**Comment by goupan1996** [comment]
> 你这是java基础常见问题，请注意查看wiki里的常见问题
嗯嗯 自己后面发现这个问题了，把common-lang3包升级了就可以了。谢谢解答！
