### ISSUE TITLE
Connection pool shutdown

### ISSUE THREAD

**Issue by Bigwty** [binarywang/WxJava#1523]
### 简要描述
使用一段时间就会报错，重启服务后可以正常运行，一段时间后又报如下错误

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:3.7.0

### 详细描述
使用一段时间就会报错，重启服务后可以正常运行，一段时间后又报如下错误
注：代码使用的demo，基本上没啥变化
### 日志
```
java.lang.IllegalStateException: Connection pool shut down
        at org.apache.http.util.Asserts.check(Asserts.java:34)
        at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:196)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:268)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at me.chanjar.weixin.mp.api.impl.WxMpServiceHttpClientImpl.getAccessToken(WxMpServiceHttpClientImpl.java:87)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:337)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:302)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getTicket(BaseWxMpServiceImpl.java:103)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getJsapiTicket(BaseWxMpServiceImpl.java:124)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.createJsapiSignature(BaseWxMpServiceImpl.java:131)
        at cn.lx.fff.wechat.controller.WxJsSdkController.getSignPackage(WxJsSdkController.java:22)
        at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by farawayll** [comment]
我也是，这个问题好久了

**Comment by binarywang** [comment]
不确定你们代码是如何写的，经过压力测试没发现有此问题。

请尽力描述清楚问题出现原因和场景

**Comment by binarywang** [comment]
看来这个问题重现几率比较高，需要深入研究下

**Comment by farawayll** [comment]
@binarywang 我的业务场景是：通过小程序的openid来发送公众号模板消息。
wxMaService.getMsgService().sendUniformMsg(wxMaUniformMessage);
出现连接池shut down的问题

**Comment by binarywang** [comment]
查阅了不少资料，最终感觉有可能是你们手动关闭了httpclient导致的，请检查下你们的代码，或者是否有什么插件自动做的，你们也许不清楚？

**Comment by SongJuDaShi** [comment]
我也是这个问题

**Comment by farawayll** [comment]
我这边的情景是这样的，每天早上8点的定时任务大概要给4000用户发送模板消息，异步的，也就是说在很短的时间里 一下怼给wxjava的消息数太多了。不知道这个是不是导致连接池shutdown的原因，但是你说你做压测没问题，看是否压测量不够，而且我这边也不是每次都出现，差不多两三天出现一次。我已经取消异步了。建议还是增加压测数或者多压测几次试试，问过给您pr的朋友，他表示wxjava支持并发比较差。发自我的iPhone------------------ Original ------------------From: Binary Wang  <notifications@github.com>Date: Sat,May 23,2020 11:17 PMTo: Wechat-Group/WxJava <WxJava@noreply.github.com>Cc: 浪浪 <13886145909@163.com>, Comment <comment@noreply.github.com>Subject: Re: [Wechat-Group/WxJava] Connection pool shutdown (#1523)
查阅了不少资料，最终感觉有可能是你们手动关闭了httpclient导致的，请检查下你们的代码，或者是否有什么插件自动做的，你们也许不清楚？

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Wechat-Group/WxJava/issues/1523#issuecomment-633074282",
"url": "https://github.com/Wechat-Group/WxJava/issues/1523#issuecomment-633074282",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Alises** [comment]
我也遇到了这个问题。但是我发现每次这个问题发生之前，都会先出现一个java.lang.StackOverflowError！
`at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at me.chanjar.weixin.common.util.http.apache.ApacheHttpClientSimpleGetRequestExecutor.execute(ApacheHttpClientSimpleGetRequestExecutor.java:39)
        at me.chanjar.weixin.common.util.http.apache.ApacheHttpClientSimpleGetRequestExecutor.execute(ApacheHttpClientSimpleGetRequestExecutor.java:19)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:324)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:339)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:284)`
不知道是只有我出现的还是所有的都遇到过

**Comment by 721806280** [comment]
> 看来这个问题重现几率比较高，需要深入研究下

请问修复了吗？同样的问题。

**Comment by lyh92** [comment]
出现问题时，之前的一个报错。 3.3.0 的版本
2020-06-10 17:06:27.879 ERROR [http-nio-10801-exec-4] o.a.c.c.C.[Tomcat].[localhost].[/].[dispatcherServlet].log:182 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError: null
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1049)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:985)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
	at javax.crypto.Cipher.doFinal(Cipher.java:2376)
	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
	at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1025)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.getAccessToken(WxMaServiceImpl.java:130)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:233)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:252)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:252)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)

**Comment by bozer666** [comment]
这个应该如何解决呢 @binarywang

**Comment by binarywang** [comment]
> 这个应该如何解决呢 @binarywang

目前无解，抱歉

**Comment by QinghuiWang** [comment]
我今天也碰到这个问题了，排查发现是由于我自己继承实现的WxMpDefaultConfigImpl子类在某种情况下会使accessToken一直是无效token，并且开启了autoRefreshToken(默认值是开启)，这样在me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl#executeInternal方法中，如果微信返回40001/42001/40014的时候会递归调用execute，最终导致栈溢出。而在 HttpClient中的MainClientExec类会最终捕获Error,并执行connManager.shutdown()，导致了PoolingHttpClientConnectionManager shut down。
希望对你们有些帮助

**Comment by binarywang** [comment]
> 我今天也碰到这个问题了，排查发现是由于我自己继承实现的WxMpDefaultConfigImpl子类在某种情况下会使accessToken一直是无效token，并且开启了autoRefreshToken(默认值是开启)，这样在me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl#executeInternal方法中，如果微信返回40001/42001/40014的时候会递归调用execute，最终导致栈溢出。而在 HttpClient中的MainClientExec类会最终捕获Error,并执行connManager.shutdown()，导致了PoolingHttpClientConnectionManager shut down。
> 希望对你们有些帮助

感谢提供重要线索，看来是跟这个有关：https://github.com/Wechat-Group/WxJava/issues/1591

**Comment by binarywang** [comment]
暂时关闭

**Comment by Arno-Li** [comment]
我遇到的问题是accessToken失效导致的死循环，然后出现java.lang.StackOverflowError！，然后就是Connection pool shut down
原因：是重写expireAccessToken设置accessToken失效的有问题
死循环原因：代码重试机制有问题，每次都会把retryTimes = 0
![image](https://user-images.githubusercontent.com/35478766/129682262-c72ad0fb-b896-439a-963c-820bdf423270.png)

![image](https://user-images.githubusercontent.com/35478766/129682123-b978f7c8-bc30-429d-bfe1-100d53183875.png)
