### ISSUE TITLE
使用wx-java-miniapp-spring-boot-starter:3.8.0必须依赖jedis

### ISSUE THREAD

**Issue by hb0730** [binarywang/WxJava#1581]
### 简要描述
在版本升级到3.8.0时config-storage中type为redistemplate启动失败
### 模块版本情况
* WxJava 模块名: 
wx-java-miniapp-spring-boot-starter
* WxJava 版本号:
3.8.0
### 详细描述
未找到redis.clients.util.Pool <br>
因为项目中使用的是lettuce连接池，并且我的config-storage指定的是Redistemplate

**Comment by binarywang** [comment]
这是个问题，稍后修复下

**Comment by binarywang** [comment]
看了下，由于代码编译需要，必须得依赖jedis，后续会将jedis作为必须依赖加入。
你可以先手动加入jedis依赖解决此问题。

**Comment by cqyisbug** [comment]
哎，jedis 有个版本改了jar包目录，真的是cao了

**Comment by hb0730** [comment]
@cqyisbug 好像只能是2.9.1一下的

**Comment by gyjx** [comment]
我今天也遇到这个问题了。并且很奇怪，springboot项目，我使用idae main方法可以运行，但是java -jar  就会报下面异常！这就导致，我本地认为没问题，运维预发环境失败。唉////

`Caused by: java.lang.NoClassDefFoundError: redis/clients/util/Pool
        at com.cd.base.wx.config.WxMpConfig.wxMpInRedisTemplateConfigStorage(WxMpConfig.java:33)
        at com.cd.base.wx.config.WxMpConfig$$EnhancerBySpringCGLIB$$f19939cb.CGLIB$wxMpInRedisTemplateConfigStorage$1(<generated>)
        at com.cd.base.wx.config.WxMpConfig$$EnhancerBySpringCGLIB$$f19939cb$$FastClassBySpringCGLIB$$f260a2e7.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.cd.base.wx.config.WxMpConfig$$EnhancerBySpringCGLIB$$f19939cb.wxMpInRedisTemplateConfigStorage(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 27 common frames omitted
`

**Comment by hb0730** [comment]
@gyjx 3.8.0 暂时只能手动依赖

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1647 跟此问题类似
