### ISSUE TITLE
ava.lang.NoSuchMethodException: com.github.config.MainConfig$$EnhancerBySpringCGLIB$$806da349.()

### ISSUE THREAD

**Issue by hbsndg** [binarywang/WxJava#159]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.config.MainConfig$$EnhancerBySpringCGLIB$$806da349]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.github.config.MainConfig$$EnhancerBySpringCGLIB$$806da349.()
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
... 22 more
Caused by: java.lang.NoSuchMethodException: com.github.config.MainConfig$$EnhancerBySpringCGLIB$$806da349.()
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.getDeclaredConstructor(Unknown Source)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
... 23 more

**Comment by ylmotol7** [comment]
这是基本的spring配置错误吧。。No default constructor found; 
就这么贴点错误代码这？

**Comment by hbsndg** [comment]
是按照这个demo下载的源码，https://github.com/Wechat-Group/weixin-java-tools-springmvc/blob/master/src/main/resources/applicationContext.xml

**Comment by binarywang** [comment]
如果是Demo的问题，麻烦请提问到对应项目下面好吗？谢谢配合～

**Comment by free2dog** [comment]
@hbsndg 添加一个 `protected MainConfig(){}` default constructor就不报错了
一句话解决的问题，不知道为什么这么新手不友好

**Comment by binarywang** [comment]
@bryce-ma https://github.com/Wechat-Group/weixin-java-tools-springmvc/issues/7 已经在这里做过回复，只是楼主自己已经不见踪影
