### ISSUE TITLE
部分请求方法会造成无限递归

### ISSUE THREAD

**Issue by shuxuefu** [binarywang/WxJava#1591]
### 简要描述
在开发过程中发现 BaseWxMpServiceImpl.execute（）调用  executeInternal方法 异常内 如果出现指定code会刷新token后调用execute（）
而execute（）方法终止条件为 为方法变量 int retryTimes = 0; 那么会如果一直出现指定code会造成无限递归

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号:3.7.0

### 详细描述

    public <T, E> T execute(RequestExecutor<T, E> executor, String uri, E data) throws WxErrorException {
        int retryTimes = 0;

        while(true) {
            try {
                return this.executeInternal(executor, uri, data);
            } catch (WxErrorException var10) {
                if (retryTimes + 1 > this.maxRetryTimes) {
                    log.warn("重试达到最大次数【{}】", this.maxRetryTimes);
                    throw new RuntimeException("微信服务端异常，超出重试次数");
                }

                WxError error = var10.getError();
                if (error.getErrorCode() != -1) {
                    throw var10;
                }

                int sleepMillis = this.retrySleepMillis * (1 << retryTimes);

                try {
                    log.warn("微信系统繁忙，{} ms 后重试(第{}次)", sleepMillis, retryTimes + 1);
                    Thread.sleep((long)sleepMillis);
                } catch (InterruptedException var9) {
                    throw new RuntimeException(var9);
                }

                if (retryTimes++ >= this.maxRetryTimes) {
                    log.warn("重试达到最大次数【{}】", this.maxRetryTimes);
                    throw new RuntimeException("微信服务端异常，超出重试次数");
                }
            }
        }
    }

    protected <T, E> T executeInternal(RequestExecutor<T, E> executor, String uri, E data) throws WxErrorException {
        E dataForLog = DataUtils.handleDataWithSecret(data);
        if (uri.contains("access_token=")) {
            throw new IllegalArgumentException("uri参数中不允许有access_token: " + uri);
        } else {
            String accessToken = this.getAccessToken(false);
            String uriWithAccessToken = uri + (uri.contains("?") ? "&" : "?") + "access_token=" + accessToken;

            try {
                T result = executor.execute(uriWithAccessToken, data, WxType.MP);
                log.debug("\n【请求地址】: {}\n【请求参数】：{}\n【响应数据】：{}", new Object[]{uriWithAccessToken, dataForLog, result});
                return result;
            } catch (WxErrorException var9) {
                WxError error = var9.getError();
                if (error.getErrorCode() == 42001 || error.getErrorCode() == 40001 || error.getErrorCode() == 40014) {
                    this.getWxMpConfigStorage().expireAccessToken();
                    if (this.getWxMpConfigStorage().autoRefreshToken()) {
                        return this.execute(executor, uri, data);
                    }
                }

                if (error.getErrorCode() != 0) {
                    log.error("\n【请求地址】: {}\n【请求参数】：{}\n【错误信息】：{}", new Object[]{uriWithAccessToken, dataForLog, error});
                    throw new WxErrorException(error, var9);
                } else {
                    return null;
                }
            } catch (IOException var10) {
                log.error("\n【请求地址】: {}\n【请求参数】：{}\n【异常信息】：{}", new Object[]{uriWithAccessToken, dataForLog, var10.getMessage()});
                throw new WxErrorException(WxError.builder().errorMsg(var10.getMessage()).build(), var10);
            }
        }
    }

**Comment by binarywang** [comment]
你是实际项目运行过程中发现有此问题吗？还只是猜测？

**Comment by lyh92** [comment]
> 你是实际项目运行过程中发现有此问题吗？还只是猜测？

java.lang.StackOverflowError: null
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1049)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:985)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
	at javax.crypto.Cipher.doFinal(Cipher.java:2376)
	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
	at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1025)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.getAccessToken(WxMaServiceImpl.java:130)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:233)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:252)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:252)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:252)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)


这个异常是吗？

**Comment by binarywang** [comment]
> > 你是实际项目运行过程中发现有此问题吗？还只是猜测？
> 
> java.lang.StackOverflowError: null
> at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1049)
> at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:985)
> at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
> at javax.crypto.Cipher.doFinal(Cipher.java:2376)
> at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
> at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
> at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1025)
> at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
> at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
> at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
> at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
> at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
> at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
> at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
> at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
> at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
> at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
> at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
> at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
> at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
> at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
> at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.getAccessToken(WxMaServiceImpl.java:130)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:233)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:252)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:252)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:252)
> at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:199)
> 
> 这个异常是吗？

明显不是，首先类不同，其次并没有无限递归，有条件的递归而已

**Comment by nengjie** [comment]
我们实际项目里面确实在这里出现了无限递归，最后导致微信的调用次数超过限制，我们最后通过链路追踪只能看到不听的递归，而递归只有可能是微信那边返回的错误码就是这里的递归条件，建议这个地方可以完善一下

**Comment by ghostg00** [comment]
我也遇到了 这个问题 假如获取的token 一直是失效的就导致 这种情况  但其实一般是想尝试一定次数 就直接异常了 这样不会占用服务资源

**Comment by binarywang** [comment]
看来出现此问题可能跟具体的配置有关系，如果配置没问题，就不会导致token一直无效，也就不会导致循环递归调用。
目前准备先增加代码把相关错误日志打印出来，以方便使用分析错误原因，从而修复配置。
