### ISSUE TITLE
分账时java.lang.NoClassDefFoundError: jodd/util/ResourcesUtil少依赖了。

### ISSUE THREAD

**Issue by ln0491** [binarywang/WxJava#1598]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名:  wx-java-pay
* WxJava 版本号: 3.8.0

### 详细描述
``

### 日志
`java.lang.NoClassDefFoundError: jodd/util/ResourcesUtil
	at com.github.binarywang.wxpay.config.WxPayConfig.initSSLContext(WxPayConfig.java:197)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.initSSLContext(WxPayServiceApacheHttpImpl.java:196)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.createHttpClientBuilder(WxPayServiceApacheHttpImpl.java:162)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.post(WxPayServiceApacheHttpImpl.java:69)
	at com.github.binarywang.wxpay.service.impl.ProfitSharingServiceImpl.profitSharing(ProfitSharingServiceImpl.java:27)
	at com.ghgcn.pay.provider.weixin.WechatPayProvider.doProfitShaingRequest(WechatPayProvider.java:784)
	at com.ghgcn.pay.provider.weixin.WechatPayProvider.profitSharing(WechatPayProvider.java:767)
	at com.ghgcn.pay.job.ProfitSharingJob.doProfitSharing(ProfitSharingJob.java:204)
	at com.ghgcn.pay.job.ProfitSharingJob.execute(ProfitSharingJob.java:94)
	at com.dangdang.ddframe.job.executor.type.SimpleJobExecutor.process(SimpleJobExecutor.java:41)
	at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.process(AbstractElasticJobExecutor.java:206)
	at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.process(AbstractElasticJobExecutor.java:171)
	at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.execute(AbstractElasticJobExecutor.java:150)
	at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.execute(AbstractElasticJobExecutor.java:122)
	at com.dangdang.ddframe.job.lite.internal.schedule.LiteJob.execute(LiteJob.java:26)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
_`

**Comment by ln0491** [comment]
我的问题，我排除了，<exclusion>
					<artifactId>jodd-http</artifactId>
					<groupId>org.jodd</groupId>
				</exclusion>

**Comment by huanghuicheng** [comment]
> 我的问题，我排除了，
> jodd-http
> org.jodd

怎么解决的

**Comment by jingshenbusi6530** [comment]
@ln0491 请问你是怎么解决的？我也出现了这个问题，我用的是3.9.0，你排除了什么？

**Comment by jingshenbusi6530** [comment]
@ln0491 而且我这个依赖是有的
 <dependency>
      <groupId>org.jodd</groupId>
      <artifactId>jodd-http</artifactId>
      <version>5.1.4</version>
      <scope>provided</scope>
    </dependency>
这个依赖，pom文件中有

**Comment by jingshenbusi6530** [comment]
我这个依赖在pom文件中是有的
`
 <dependency>
      <groupId>org.jodd</groupId>
      <artifactId>jodd-http</artifactId>
      <version>5.1.4</version>
      <scope>provided</scope>
   </dependency>
`
