### ISSUE TITLE
3.8.0版本自带的common-lang.lang3-3.7.0缺失RegExUtils

### ISSUE THREAD

**Issue by shz313299639** [binarywang/WxJava#1637]
### 简要描述
com.github.binarywang.wxpay.config.WxPayConfig  中引用了 org.apache.commons.lang3.RegExUtils ，但是3.8.0自带的是org.apache.commons:commons-lang3:3.7。。
RegExUtils  @since 3.8。

### 模块版本情况
* WxJava 模块名: weixin-java-pay:3.8.0
* WxJava 版本号:3.8.0

### 详细描述
3.8.0 版本自带的commo-lang3版本过低，至少需要升级到3.8。。不然会出现org.apache.commons.lang3.RegExUtils 找不到的错误。

### 日志
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/RegExUtils
	at com.github.binarywang.wxpay.config.WxPayConfig.initSSLContext(WxPayConfig.java:192)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.initSSLContext(WxPayServiceApacheHttpImpl.java:196)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.createHttpClientBuilder(WxPayServiceApacheHttpImpl.java:162)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.post(WxPayServiceApacheHttpImpl.java:69)
	at com.github.binarywang.wxpay.service.impl.EntPayServiceImpl.entPay(EntPayServiceImpl.java:50)
	at com.giot.yytourism.finance.controller.AuditingAppController.withdraw(AuditingAppController.java:112)
	at com.giot.yytourism.finance.controller.AuditingAppController$$FastClassBySpringCGLIB$$843cd075.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.giot.yytourism.finance.controller.AuditingAppController$$EnhancerBySpringCGLIB$$183fa6ea.withdraw(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	... 90 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.RegExUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 116 common frames omitted

**Comment by binarywang** [comment]
请仔细看清楚版本依赖，https://github.com/Wechat-Group/WxJava/blob/master/pom.xml
目前明显用的是3.10，否则按你所说的低版本，编译都无法通过，更不可能打包发布成功的

**Comment by binarywang** [comment]
```

      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <version>3.10</version>
      </dependency>
```

**Comment by github-0paul** [comment]
@binarywang 版本依赖有问题哈，3.10并没有起作用
