### ISSUE TITLE
调用小程序解密用户手机号接口，Gson解析偶尔出现异常

### ISSUE THREAD

**Issue by xuxinlong001** [binarywang/WxJava#1666]
### 简要描述
调用小程序解密用户手机号接口，Gson偶尔出现异常
### 模块版本情况
* WxJava 模块名:  wx-java-miniapp-spring-boot-starter
* WxJava 版本号:  3.8.0其他版本也同样有这个问题

### 详细描述
接口：wxMaService.getUserService().getPhoneNoInfo()
第一次授权手机号时总会异常，第二次就好了，打断点发现报错是解析时会出现乱码导致的

### 日志
2020-07-13 17:13:56,351 [http-nio-8080-exec-3] ERROR c.p.c.e.GlobalExceptionHandler 112 - java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at cn.binarywang.wx.miniapp.bean.WxMaPhoneNumberInfo.fromJson(WxMaPhoneNumberInfo.java:23)
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getPhoneNoInfo(WxMaUserServiceImpl.java:56)

**Comment by binarywang** [comment]
请参考置顶区的问题，不要重复提问题

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/359
