### ISSUE TITLE
调用qrCodeCreateTmpTicket报NullPointerException

### ISSUE THREAD

**Issue by wangfengfly** [binarywang/WxJava#167]
外部调用代码段：
MainConfig mConfig = new MainConfig();
wxMpService = mConfig.wxMpService();
WxMpQrCodeTicket ticket = wxMpService.getQrcodeService().qrCodeCreateTmpTicket(1, 240);

报如下异常信息：
java.lang.NullPointerException
at me.chanjar.weixin.mp.api.impl.WxMpServiceImpl.getAccessToken(WxMpServiceImpl.java:115)
at me.chanjar.weixin.mp.api.impl.WxMpServiceImpl.executeInternal(WxMpServiceImpl.java:402)
at me.chanjar.weixin.mp.api.impl.WxMpServiceImpl.execute(WxMpServiceImpl.java:368)
at me.chanjar.weixin.mp.api.impl.WxMpQrcodeServiceImpl.qrCodeCreateTmpTicket(WxMpQrcodeServiceImpl.java:45)
at com.sitewhere.web.mvc.controllers.EduInterfaceController.code(EduInterfaceController.java:142)

其中WxMpServiceImpl.java:115如下：
CloseableHttpResponse response = getHttpclient().execute(httpGet);
            String resultContent = new BasicResponseHandler().handleResponse(response);
            WxError error = WxError.fromJson(resultContent);
            **if (error.getErrorCode() != 0) {**
              throw new WxErrorException(error);
            }

**Comment by binarywang** [comment]
你用的是哪个版本？我刚试了develop分支上的版本，没有问题，代码行数也不匹配。你先用最新版本试试吧

**Comment by wangfengfly** [comment]
谢谢，问题已解决
