### ISSUE TITLE
3.8.0版微信小程序登录报错

### ISSUE THREAD

**Issue by wenyuantc** [binarywang/WxJava#1691]
public static WxMaUserInfo fromJson(String json) {
    return WxMaGsonBuilder.create().fromJson(json, WxMaUserInfo.class);
  }

json信息转换的时候报错
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected value at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at cn.binarywang.wx.miniapp.bean.WxMaUserInfo.fromJson(WxMaUserInfo.java:27)
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getUserInfo(WxMaUserServiceImpl.java:33)

**Comment by thislyc** [comment]
我也遇到了 请问有解决方案吗

**Comment by thislyc** [comment]
[https://www.cnblogs.com/guansixu/articles/6484872.html](https://www.cnblogs.com/guansixu/articles/6484872.html)
看到了之前的issues提供的方法 亲测可行

**Comment by binarywang** [comment]
注意看置顶区问题
