### ISSUE TITLE
微信解码错误

### ISSUE THREAD

**Issue by lvdong** [binarywang/WxJava#1731]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
微信解码时会报以下这个错误

### 模块版本情况
* WxJava 模块名:  mp
* WxJava 版本号:3.9

### 详细描述
使用最新版的时候

### 日志
java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 41
        at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:219) ~[guava-29.0-jre.jar!/:na]
        at me.chanjar.weixin.mp.util.crypto.WxMpCryptUtil.<init>(WxMpCryptUtil.java:43) ~[weixin-java-mp-3.9.0.jar!/:na]
        at me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromEncryptedXml(WxMpXmlMessage.java:708) ~[weixin-java-mp-3.9.0.jar!/:na]
        at com.yssoo.lims.modules.mp.controller.WxPortalController.handleMessage(WxPortalController.java:128) ~[yssoo-lims-modules-mp-0.0.1-SNAPSHOT.jar!/:na]
        at com.yssoo.lims.modules.mp.controller.WxPortalController.post(WxPortalController.java:84) ~[yssoo-lims-modules-mp-0.0.1-SNAPSHOT.jar!/:na]
        at com.yssoo.lims.modules.mp.controller.WxPortalController$$FastClassBySpringCGLIB$$8402d20.invoke(<generated>) ~[yssoo-lims-modules-mp-0.0.1-SNAPSHOT.jar!/:na]

**Comment by binarywang** [comment]
请仔细描述下问题产生过程？

**Comment by lvdong** [comment]
项目一开始用的版本是3.8，jdk是11,  然后在微信加解密时会报java.security.InvalidKeyException: Illegal key size这个错误，就是简单的关注事件，后来按照 wiki上指引查看自己jdk，发现默认crypto.policy=unlimited是开着的。所以我想是不是版本问题。所以就升级到最新版本。升级到最新版本后发现错误就不一样了，就会报com.google.common.io.BaseEncoding$DecodingException: Invalid input length 41 这个错误，这种情况是不是要换jdk?

**Comment by binarywang** [comment]
你找到问题解决方法了？
