### ISSUE TITLE
wx-java-mp-spring-boot-starter使用redistemplate做存储报错

### ISSUE THREAD

**Issue by leezicheng** [binarywang/WxJava#1736]
### 简要描述

wx-java-mp-spring-boot-starter中，config-storage策略使用redistemplate报错。

### 模块版本情况
* WxJava 模块名: wx-java-mp-spring-boot-starter
* WxJava 版本号:3.9.0

### 详细描述

使用wx-java-mp-spring-boot-starter进行公众号开发，使用存储配置为redistemplate，
系统能正常启动，业务种触发getAccessToken()操作时，存入AccessToken到Redis时报错，信息如下：
`Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[BLorg/springframework/data/redis/core/types/Expiration;Lorg/springframework/data/redis/connection/RedisStringCommands$SetOption;)V
`
定位后发现，weixin-java-common模块的reids依赖了parent
```
  <parent>
    <groupId>com.github.binarywang</groupId>
    <artifactId>wx-java</artifactId>
    <version>3.9.0</version>
  </parent>

```
而wx-java中的redis版本如下：

```
      <dependency>
        <groupId>org.springframework.data</groupId>
        <artifactId>spring-data-redis</artifactId>
        <version>1.8.23.RELEASE</version>
        <optional>true</optional>
        <scope>provided</scope>
      </dependency>
```

我项目中使用的springboot版本为2.3.0.RELEASE，检查了包依赖，并没有发现冲突。

我认为是Spring-data-redis 2.0版本中set(String,String)方法被弃用了，请帮我看看是什么问题谢谢。

### 详细错误堆栈
`2020-09-02 20:47:02.280 ERROR 8700 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[BLorg/springframework/data/redis/core/types/Expiration;Lorg/springframework/data/redis/connection/RedisStringCommands$SetOption;)V] with root cause

java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[BLorg/springframework/data/redis/core/types/Expiration;Lorg/springframework/data/redis/connection/RedisStringCommands$SetOption;)V
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock$1.doInRedis(RedisTemplateSimpleDistributedLock.java:82) ~[weixin-java-common-3.9.0.jar:na]
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock$1.doInRedis(RedisTemplateSimpleDistributedLock.java:79) ~[weixin-java-common-3.9.0.jar:na]
	at org.springframework.data.redis.core.RedisTemplate.lambda$executePipelined$1(RedisTemplate.java:328) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:175) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:324) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:314) ~[spring-data-redis-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.tryLock(RedisTemplateSimpleDistributedLock.java:79) ~[weixin-java-common-3.9.0.jar:na]
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.tryLock(RedisTemplateSimpleDistributedLock.java:94) ~[weixin-java-common-3.9.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.WxMpServiceHttpClientImpl.getAccessToken(WxMpServiceHttpClientImpl.java:76) ~[weixin-java-mp-3.9.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:336) ~[weixin-java-mp-3.9.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:301) ~[weixin-java-mp-3.9.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:275) ~[weixin-java-mp-3.9.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:280) ~[weixin-java-mp-3.9.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.WxMpQrcodeServiceImpl.getQrCodeTicket(WxMpQrcodeServiceImpl.java:80) ~[weixin-java-mp-3.9.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.WxMpQrcodeServiceImpl.qrCodeCreateLastTicket(WxMpQrcodeServiceImpl.java:92) ~[weixin-java-mp-3.9.0.jar:na]
	at com.example.demo.controller.TestController.test(TestController.java:28) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.35.jar:9.0.35]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

`

**Comment by tangchangyuan** [comment]
同问

**Comment by panpan-w** [comment]
同问

**Comment by dushuai1128** [comment]
这个问题,困扰我一周了

**Comment by yangleicd123** [comment]
我也遇到这个问题,请问解决了吗?

**Comment by yang20029798** [comment]
同问，求解决

**Comment by binarywang** [comment]
这么多人同时回复呢？这个估计跟版本冲突有关系，晚会儿有空看下

**Comment by binarywang** [comment]
经过测试并没有发现问题，请参考 https://github.com/binarywang/wx-java-mp-demo 这个demo

**Comment by binarywang** [comment]
注意选择正确匹配的  `spring-boot-starter-data-redis` 版本

**Comment by tangchangyuan** [comment]
package com.binarywang.demo.wx.mp;

import me.chanjar.weixin.common.error.WxErrorException;
import me.chanjar.weixin.mp.api.WxMpService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * @author binary wang
 */
@RestController
@RequestMapping("/")
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Autowired
    private WxMpService mpService;

    @GetMapping("/test")
    public String getAppId() {
        this.mpService.getWxMpConfigStorage().getAppId();
        try {
            this.mpService.getAccessToken();  //像这样调用就会抛出异常
        } catch (WxErrorException e) {
            e.printStackTrace();
        }
        return null;
    }
}


java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[BLorg/springframework/data/redis/core/types/Expiration;Lorg/springframework/data/redis/connection/RedisStringCommands$SetOption;)V

**Comment by lkqm** [comment]
提供下打包后的spring-data-redis版本是多少，目前该方法只在1.7和1.7+以上才有`void set(byte[] key, byte[] value, Expiration expiration, SetOption option);`

**Comment by binarywang** [comment]
请使用最新版本 3.9.1.B，同时 https://github.com/binarywang/wx-java-mp-demo 这个demo也已更新，暂时没发现问题

**Comment by tangchangyuan** [comment]
谢谢

**Comment by leezicheng** [comment]
谢谢
