### ISSUE TITLE
me.chanjar.weixin.common.util.fs包下的createTmpFile方法报错

### ISSUE THREAD

**Issue by cksspk** [binarywang/WxJava#1742]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
在获取二维码的时候qrcodeService.qrCodePicture(wxMpQrCodeTicket);
方法报错
### 模块版本情况
* WxJava 模块名: weixin-java-common
* WxJava 版本号:3.9.0

### 详细描述
在获取二维码的时候qrcodeService.qrCodePicture(wxMpQrCodeTicket);
方法报错，跟进代码发现
```
  public static File createTmpFile(InputStream inputStream, String name, String ext, File tmpDirFile) throws IOException {
    File resultFile = File.createTempFile(name, '.' + ext, tmpDirFile);

    resultFile.deleteOnExit();
    org.apache.commons.io.FileUtils.copyToFile(inputStream, resultFile);
    return resultFile;
  }
```
` org.apache.commons.io.FileUtils.copyToFile(inputStream, resultFile);`报错。
报错信息如下：
`java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyToFile(Ljava/io/InputStream;Ljava/io/File;)V
	at me.chanjar.weixin.common.util.fs.FileUtils.createTmpFile(FileUtils.java:23)
	at me.chanjar.weixin.common.util.fs.FileUtils.createTmpFile(FileUtils.java:35)
	at me.chanjar.weixin.mp.util.requestexecuter.qrcode.QrCodeApacheHttpRequestExecutor.execute(QrCodeApacheHttpRequestExecutor.java:61)
	at me.chanjar.weixin.mp.util.requestexecuter.qrcode.QrCodeApacheHttpRequestExecutor.execute(QrCodeApacheHttpRequestExecutor.java:28)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:340)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:301)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:290)
	at me.chanjar.weixin.mp.api.impl.WxMpQrcodeServiceImpl.qrCodePicture(WxMpQrcodeServiceImpl.java:102)
	at com.ckss.project.weixin.controller.WxLoginController.getQrCode(WxLoginController.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:873)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)`

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by cksspk** [comment]
> ### 简要描述
> 在获取二维码的时候qrcodeService.qrCodePicture(wxMpQrCodeTicket);
> 方法报错
> 
> ### 模块版本情况
> * WxJava 模块名: weixin-java-common
> * WxJava 版本号:3.9.0
> 
> ### 详细描述
> 在获取二维码的时候qrcodeService.qrCodePicture(wxMpQrCodeTicket);
> 方法报错，跟进代码发现
> 
> ```
>   public static File createTmpFile(InputStream inputStream, String name, String ext, File tmpDirFile) throws IOException {
>     File resultFile = File.createTempFile(name, '.' + ext, tmpDirFile);
> 
>     resultFile.deleteOnExit();
>     org.apache.commons.io.FileUtils.copyToFile(inputStream, resultFile);
>     return resultFile;
>   }
> ```
> 
> ` org.apache.commons.io.FileUtils.copyToFile(inputStream, resultFile);`报错。
> 报错信息如下：
> `java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyToFile(Ljava/io/InputStream;Ljava/io/File;)V at me.chanjar.weixin.common.util.fs.FileUtils.createTmpFile(FileUtils.java:23) at me.chanjar.weixin.common.util.fs.FileUtils.createTmpFile(FileUtils.java:35) at me.chanjar.weixin.mp.util.requestexecuter.qrcode.QrCodeApacheHttpRequestExecutor.execute(QrCodeApacheHttpRequestExecutor.java:61) at me.chanjar.weixin.mp.util.requestexecuter.qrcode.QrCodeApacheHttpRequestExecutor.execute(QrCodeApacheHttpRequestExecutor.java:28) at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:340) at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:301) at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:290) at me.chanjar.weixin.mp.api.impl.WxMpQrcodeServiceImpl.qrCodePicture(WxMpQrcodeServiceImpl.java:102) at com.ckss.project.weixin.controller.WxLoginController.getQrCode(WxLoginController.java:78) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:873) at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:858) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)`
> 
> ### 日志
> **将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里**

**Comment by binarywang** [comment]
你这是常见问题，看wiki就清楚了

**Comment by cksspk** [comment]
> 你这是常见问题，看wiki就清楚了

感谢回复。
刚才去wiki里面找了好一会儿，应该是我太笨了，没找到问题解决办法。或者说我寻找的方法有问题。
如果您有时间，可以发一下链接吗？
这是问题的图片：
![微信截图_20200906171113](https://user-images.githubusercontent.com/37790595/92322592-be666980-f064-11ea-8eac-45296582a27c.png)


谢谢。

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/wiki/NoClassDefFoundError%E3%80%81NoSuchMethodError%E6%88%96ClassNotFoundException%E7%AD%89%E5%BC%82%E5%B8%B8%E7%9A%84%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95

**Comment by cksspk** [comment]
> https://github.com/Wechat-Group/WxJava/wiki/NoClassDefFoundError%E3%80%81NoSuchMethodError%E6%88%96ClassNotFoundException%E7%AD%89%E5%BC%82%E5%B8%B8%E7%9A%84%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95

 #谢谢，我找到问题在哪里了。
