### ISSUE TITLE
weixin-java-common 3.9.0将spring-data-redis 1.x升级到2.x

### ISSUE THREAD

**Issue by prosaically** [binarywang/WxJava#1748]
### 简要描述
spring-data-redis 1.x跟2.x版本不兼容，Jedis 3.x 需要spring-data-redis 2.2.x来支持。
weixin-java使用使用的是spring-data-redis 1.8.23，无法使用Jedis 3.x，将spring-data-redis依赖版本升级2.x又出现spring-data-redis 1.x跟2.x不兼容。
所以建议将weixin-java的spring-data-redis版本升级到2.x，或者说两个分支。

#### Jedis 2.x 跟 3.x不兼容原因
Pool包路径不同
```
// 3.x
redis.clients.util.Pool
// 2.x
redis.clients.util.Pool
``` 
异常日志
```
java.lang.NoClassDefFoundError: redis/clients/util/Pool

	at com.exemple.test.Tests.init(Tests.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: redis.clients.util.Pool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```
#### spring-data-redis 1.x 跟 2.x不兼容原因
RedisStringCommands方法返回值不同
```
// 2.x
Boolean set(byte[] key, byte[] value, Expiration expiration, SetOption option);
// 1.x
void set(byte[] key, byte[] value, Expiration expiration, SetOption option);
``` 
异常日志
```
java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[BLorg/springframework/data/redis/core/types/Expiration;Lorg/springframework/data/redis/connection/RedisStringCommands$SetOption;)V

	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock$1.doInRedis(RedisTemplateSimpleDistributedLock.java:82)
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock$1.doInRedis(RedisTemplateSimpleDistributedLock.java:79)
	at org.springframework.data.redis.core.RedisTemplate.lambda$executePipelined$1(RedisTemplate.java:324)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:320)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:310)
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.tryLock(RedisTemplateSimpleDistributedLock.java:79)
	at com.exemple.test.Tests.testLock(Tests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```
#### weixin-java-common异常原因
RedisTemplateSimpleDistributedLock中tryLock方法使用了RedisConnection.set方法。
weixin-java使用spring-data-redis 1.8.23，set方法的返回值是void，使用weixin-java的项目使用spring-data-redis 2.x时set方法的返回值是Boolean。
weixin-java是maven依赖的jar，使用的项目编译并不会修改jar，所以就会出现java.lang.NoSuchMethodError

#### 以上仅个人见解，如果有考虑不周的地方，还请指正。谢谢！

**Comment by binarywang** [comment]
你描述了这么多，其实上周刚发布了新的测试版本3.9.1.B，已解决了此问题，具体还可以参考这个issue https://github.com/Wechat-Group/WxJava/issues/1736

**Comment by prosaically** [comment]
好的，非常感谢！
