### ISSUE TITLE
收到微信消息时解析错误

### ISSUE THREAD

**Issue by btboys** [binarywang/WxJava#1757]
```java
Caused by: org.xml.sax.SAXNotRecognizedException: unrecognized feature http://apache.org/xml/features/disallow-doctype-decl
        at org.gjt.xpp.sax2.Driver.setFeature(Driver.java:178) ~[pull-parser-2.jar!/:na]
        at org.dom4j.io.SAXReader.setFeature(SAXReader.java:283) ~[dom4j-2.1.3.jar!/:na]
        at me.chanjar.weixin.common.util.XmlUtils.xml2Map(XmlUtils.java:34) ~[weixin-java-common-3.9.0.jar!/:na]
        ... 100 common frames omitted
```

**Comment by binarywang** [comment]
请参考#1734

**Comment by wjzjames** [comment]
请问解决了吗？
