### ISSUE TITLE
小程序获取用户信息

### ISSUE THREAD

**Issue by daizhihua-huan** [binarywang/WxJava#1765]
第一次获取的时候总是报错验证失败 第二次验证成功
![Uploading [image.png…]()](url)

![image](https://user-images.githubusercontent.com/59756432/93091148-52bd7580-f6d0-11ea-8f4f-86aa62cfc0ca.png)

**Comment by daizhihua-huan** [comment]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 90 more

**Comment by binarywang** [comment]
楼主可否看下wiki常见问题，或者issues置顶问题
