### ISSUE TITLE
WxMaAutoConfiguration 加载出了一个全是null的微信配置

### ISSUE THREAD

**Issue by balzaron** [binarywang/WxJava#1791]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
启动springboot 时候自己的appid和key都顺利加载了，但是报了个NPE， 里面是一个空的微信配置，感觉是WxMaAutoConfiguration加载出来的。

### 模块版本情况
* WxJava 模块名:  miniapp
* WxJava 版本号: 3.9.4.B

### 详细描述
```java
Caused by: java.lang.NullPointerException: null key in entry: null={"accessTokenLock":{"sync":{"state":0}},"expiresTime":0,"httpProxyPort":0,"jsapiTicketExpiresTime":0,"cardApiTicketExpiresTime":0,"jsapiTicketLock":{"sync":{"state":0}},"cardApiTicketLock":{"sync":{"state":0}}}
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:30)
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42)
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:72)
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:124)
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.setWxMaConfig(BaseWxMaServiceImpl.java:306)
	at com.binarywang.spring.starter.wxjava.miniapp.config.WxMaAutoConfiguration.service(WxMaAutoConfiguration.java:70)
	at com.binarywang.spring.starter.wxjava.miniapp.config.WxMaAutoConfiguration$$EnhancerBySpringCGLIB$$65aea87c.CGLIB$service$0(<generated>)
	at com.binarywang.spring.starter.wxjava.miniapp.config.WxMaAutoConfiguration$$EnhancerBySpringCGLIB$$65aea87c$$FastClassBySpringCGLIB$$fcf81c2d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.binarywang.spring.starter.wxjava.miniapp.config.WxMaAutoConfiguration$$EnhancerBySpringCGLIB$$65aea87c.service(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 62 more
```
### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
明显是配置有问题，没读到，导致key为空，自己仔细检查下就知道了
