### ISSUE TITLE
调用WxMpService的临时素材下载方法无效,提示错误代码:99999,文件名不存在

### ISSUE THREAD

**Issue by Binaryang-one** [binarywang/WxJava#1796]
前端上传临时素材后回调获取的serverId直接传给后端

服务端调用方法如下：
File file = wxMpService.getMaterialService().mediaDownload(serverId);

提示错误代码:99999,文件名不存在

目前能确认的是appid和secret前后端是一致的

**Comment by Binaryang-one** [comment]
前端这边使用的JS-SDK调用的上传语音接口
wx.uploadVoice({
  localId: '', // 需要上传的音频的本地ID，由stopRecord接口获得
  isShowProgressTips: 1, // 默认为1，显示进度提示
  success: function (res) {
    var serverId = res.serverId; // 返回音频的服务器端ID
  }
});
这里回调的serverId然后传给后端,但一直都报错

**Comment by binarywang** [comment]
请给出完整错误信息，包括异常堆栈内容，可以看出是哪一行报的错

**Comment by binarywang** [comment]
没有详细信息，无法帮忙定位，长时间没回复，关闭

**Comment by linlipeng557** [comment]
Caused by: me.chanjar.weixin.common.error.WxErrorException: 错误代码：99999, 错误信息：无法获取到文件名
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:61)
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:43)
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:61)
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:30)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:340)
