### ISSUE TITLE
错误代码：99999, 错误信息：无法获取到文件名

### ISSUE THREAD

**Issue by linlipeng557** [binarywang/WxJava#1808]
### 简要描述
前端提交的语音，后端下载失败，提示无法获取文件名（前端没问题，前端在另一个项目中使用着，但是后端不是用wxjava的）

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号:3.9.0

错误定位
Caused by: me.chanjar.weixin.common.error.WxErrorException: 错误代码：99999, 错误信息：无法获取到文件名
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:61)
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:43)
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:61)
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:30)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:340)

**Comment by binarywang** [comment]
相关代码经过单元测试没有问题，请参考`me.chanjar.weixin.mp.api.impl.WxMpMaterialServiceImplTest#testDownloadMedia`
