### ISSUE TITLE
WxCpServiceImpl 获取token报错

### ISSUE THREAD

**Issue by chenweinan121** [binarywang/WxJava#1818]
[java.lang.RuntimeException: java.net.SocketException: Connection reset
	at me.chanjar.weixin.cp.api.impl.WxCpServiceImpl.getAccessToken(WxCpServiceImpl.java:71)
	at me.chanjar.weixin.cp.api.impl.BaseWxCpServiceImpl.getAccessToken(BaseWxCpServiceImpl.java:95)

在不同服务器上，相同企业微信配置，相同的jar包 ，qyapi.weixin.qq.com是可以ping通的 但是一个环境报错，另一个环境不报错

**Comment by binarywang** [comment]
这种错误明显跟网络环境相关，建议仔细检查区别
