### ISSUE TITLE
在Handler里面调用controller里面的方法报空指针

### ISSUE THREAD

**Issue by VesperHan** [binarywang/WxJava#234]
在MsgHandler里面调用新建的Controller里面的方法,每次调用都空指针
--MsgHander
       WxMenuController menuController = new WxMenuController();
        String meida_id = menuController.getNewsMaterialList_MediaId();

--Controller类有注解@Autowrite @RESRController
是语法问题么?
还是注解问题,,麻烦楼主分析一下
**java.lang.NullPointerException**
	at com.github.binarywang.demo.spring.controller.**WxMenuController.getNewsMaterialList_MediaId**(WxMenuController.java:79)
	at com.github.binarywang.demo.spring.handler.MsgHandler.handle(MsgHandler.java:59)
	at me.chanjar.weixin.mp.api.WxMpMessageRouterRule.service(WxMpMessageRouterRule.java:217)
	at me.chanjar.weixin.mp.api.WxMpMessageRouter.route(WxMpMessageRouter.java:172)
	at com.github.binarywang.demo.spring.service.WeixinService.route(WeixinService.java:142)
	at com.github.binarywang.demo.spring.controller.WxMpPortalController.post(WxMpPortalController.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)

**Comment by binarywang** [comment]
楼主，你自己写的代码也没贴出代码，如何给你分析？而且WxMenuController 你是要用new来生成吗？

**Comment by binarywang** [comment]
没有进一步信息可以跟踪，暂时关闭
