### ISSUE TITLE
miniapp 模块 发送模板消息， 解析微信服务器返回结果空指针

### ISSUE THREAD

**Issue by ruying408** [binarywang/WxJava#260]
java.lang.NullPointerException: null at cn.binarywang.wx.miniapp.api.impl.WxMaMsgServiceImpl.sendTemplateMsg(WxMaMsgServiceImpl.java:34) ~[weixin-java-miniapp-2.7.0.jar:na]
        at com.github.binarywang.demo.wechat.controller.WxPortalController.sendMsg(WxPortalController.java:108) ~[classes/:1.0.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]

**Comment by kareanyi** [comment]
看了下文档，这里取错了
if (jsonObject.get("errcode").getAsInt() == 0) {
      return jsonObject.get("msgid").getAsString();
}

文档上写的是
{
  "errcode": 0,
  "errmsg": "ok",
}

**Comment by binarywang** [comment]
我看了下，确实是有问题，这块儿忘了仔细核对，从公众号代码那里参考过来的。

**Comment by kareanyi** [comment]
嗯，那块应该就不用return了

**Comment by binarywang** [comment]
2.7.2.BETA版本已修复
