### ISSUE TITLE
NoHttpResponseException: api.weixin.qq.com:443 failed to respond

### ISSUE THREAD

**Issue by lijunhaos** [binarywang/WxJava#276]
我是在发送微信模板消息的时候遇到这个问题的。求助：

```

java.lang.RuntimeException: org.apache.http.NoHttpResponseException: api.weixin.qq.com:443 failed to respond
    at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.executeInternal(AbstractWxMpServiceImpl.java:314)
    at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.execute(AbstractWxMpServiceImpl.java:251)
    at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.post(AbstractWxMpServiceImpl.java:241)
    at me.chanjar.weixin.mp.api.impl.WxMpTemplateMsgServiceImpl.sendTemplateMsg(WxMpTemplateMsgServiceImpl.java:34)
    at com.liuceng.zen.service.CustomerNotifyService.ciNotifyWxSenderToBackend(CustomerNotifyService.java:239)
    at com.liuceng.zen.service.CustomerNotifyService.ciNotifyWxSenderOnBackend(CustomerNotifyService.java:174)
    at com.liuceng.zen.service.CustomerNotifyService.ciNotifyWxSender(CustomerNotifyService.java:91)
    at com.liuceng.zen.service.CustomerNotifyService.getCustomerNotifyMessage(CustomerNotifyService.java:75)
    at sun.reflect.GeneratedMethodAccessor228.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.invokeListenerMethod(MessageListenerAdapter.java:387)
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:298)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:777)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:700)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:95)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:187)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1187)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:681)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1165)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1149)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1100(SimpleMessageListenerContainer.java:95)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1312)
    at java.lang.Thread.run(Thread.java:745)
org.apache.http.NoHttpResponseException: api.weixin.qq.com:443 failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
    at me.chanjar.weixin.common.util.http.apache.ApacheSimplePostRequestExecutor.execute(ApacheSimplePostRequestExecutor.java:39)
    at me.chanjar.weixin.common.util.http.apache.ApacheSimplePostRequestExecutor.execute(ApacheSimplePostRequestExecutor.java:20)
    at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.executeInternal(AbstractWxMpServiceImpl.java:288)
    at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.execute(AbstractWxMpServiceImpl.java:251)
    at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.post(AbstractWxMpServiceImpl.java:241)
    at me.chanjar.weixin.mp.api.impl.WxMpTemplateMsgServiceImpl.sendTemplateMsg(WxMpTemplateMsgServiceImpl.java:34)
    at com.liuceng.zen.service.CustomerNotifyService.ciNotifyWxSenderToBackend(CustomerNotifyService.java:239)
    at com.liuceng.zen.service.CustomerNotifyService.ciNotifyWxSenderOnBackend(CustomerNotifyService.java:174)
    at com.liuceng.zen.service.CustomerNotifyService.ciNotifyWxSender(CustomerNotifyService.java:91)
    at com.liuceng.zen.service.CustomerNotifyService.getCustomerNotifyMessage(CustomerNotifyService.java:75)
    at sun.reflect.GeneratedMethodAccessor228.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.invokeListenerMethod(MessageListenerAdapter.java:387)
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:298)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:777)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:700)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:95)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:187)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1187)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:681)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1165)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1149)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1100(SimpleMessageListenerContainer.java:95)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1312)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by bysunexus** [comment]
FIY:

[https://stackoverflow.com/questions/10558791/apache-httpclient-interim-error-nohttpresponseexception?answertab=votes](https://stackoverflow.com/questions/10558791/apache-httpclient-interim-error-nohttpresponseexception?answertab=votes)
[https://my.oschina.net/sannychan/blog/485677](https://my.oschina.net/sannychan/blog/485677)

因为设置了连接池 请根据自己的情况配置一下超时情况或者是设置retry

**Comment by lijunhaos** [comment]
ok,   谢谢了

**Comment by AabbyAngel** [comment]
请问这个问题如何解决的？

**Comment by binarywang** [comment]
请参考kakotor的解决方案

**Comment by sunyaf** [comment]
我也遇到这个问题了，我是在多线程的时候遇到这个问题的，我想彻底的解决这个问题，但是不清楚这个问题发生的原因是什么，你解决了吗，谢谢，期待你的回复

**Comment by jianhong-li** [comment]
http://firfor.cn/articles/2019/05/19/1558271846111.html
长链接的超时时间(keep-alive)设定有问题.参考这个文章.

**Comment by haoyanbing** [comment]
参考kakotor提供的方法，添加重试策略或者修改超时时间，但是我发现默认使用的ApacheHttpClient，提供了一个构造器：DefaultApacheHttpClientBuilder，但是该构造器没有提供可以设置 HttpRequestRetryHandler 和 设置 setKeepAliveStrategy，后面版本有没有优化这个。而且默认的重试策略是 不重试。

**Comment by binarywang** [comment]
> 参考kakotor提供的方法，添加重试策略或者修改超时时间，但是我发现默认使用的ApacheHttpClient，提供了一个构造器：DefaultApacheHttpClientBuilder，但是该构造器没有提供可以设置 HttpRequestRetryHandler 和 设置 setKeepAliveStrategy，后面版本有没有优化这个。而且默认的重试策略是 不重试。

这个想法不错，建议直接PR
