### ISSUE TITLE
xstream中的Mapper和mybatisplus中的Mapper冲突，启动失败

### ISSUE THREAD

**Issue by minliuhua** [binarywang/WxJava#3051]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
__请简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:  4.4.0

### 详细描述
xstream中的Mapper和mybatisplus中的Mapper冲突，启动失败

### 日志
```
org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'mapper' for bean class [com.thoughtworks.xstream.mapper.Mapper] conflicts with existing, non-compatible bean definition of same name and class [com.baomidou.mybatisplus.core.mapper.Mapper]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349)
	at org.mybatis.spring.mapper.ClassPathMapperScanner.checkCandidate(ClassPathMapperScanner.java:256)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287)
	at org.mybatis.spring.mapper.ClassPathMapperScanner.doScan(ClassPathMapperScanner.java:181)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.scan(ClassPathBeanDefinitionScanner.java:254)
	at org.mybatis.spring.mapper.MapperScannerConfigurer.postProcessBeanDefinitionRegistry(MapperScannerConfigurer.java:356)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.zh.ZhjtFcsyApplication.main(ZhjtFcsyApplication.java:34)
Disconnected from the target VM, address: '127.0.0.1:64525', transport: 'socket'

```

**Comment by binarywang** [comment]
要看你下你的代码怎么写的，为什么会需要将xtream的mapper给spring管理？

**Comment by huangzhaoyi** [comment]
> 要看你下你的代码怎么写的，为什么会需要将xtream的mapper给spring管理？

出现了同样的错误，程序没有刻意将xtream的mapper给spring管理，springboot3+jdk21版本,扫描包配置了也无效
