### ISSUE TITLE
AbstractWxMpServiceImpl.java 递归问题

### ISSUE THREAD

**Issue by yuzhuguan** [binarywang/WxJava#313]
me.chanjar.weixin.common.exception.WxErrorException: {"errcode":45009,"errmsg":"reach max api daily quota limit hint: [1yGX4a0011e514]"}
	at com.cosmos.weixin.config.CosmosWxMpServiceImpl.getAccessToken(CosmosWxMpServiceImpl.java:89)
	at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.executeInternal(AbstractWxMpServiceImpl.java:283)
	at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.execute(AbstractWxMpServiceImpl.java:251)
	at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.executeInternal(AbstractWxMpServiceImpl.java:303)
	at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.execute(AbstractWxMpServiceImpl.java:251)
	at me.chanjar.weixin.mp.api.impl.AbstractWxMpServiceImpl.executeInternal(AbstractWxMpServiceImpl.java:303)
.... 
当出问题时， 会反复获取token， 如果config设置autoRefreshToken 为true时， 会导致测试号的token request 很快达到微信的2000次/天

**Comment by binarywang** [comment]
你确定不是你自己代码的问题？

**Comment by yuzhuguan** [comment]
sorry, 回复晚了， 我自己的问题， 由于ide看到的代码是反编译的， 我继承时，直接复制的反编译的代码， 把if else 复制成while了， 不好意思。 关闭吧
