### ISSUE TITLE
获取小程序二维码失败

### ISSUE THREAD

**Issue by totzcc** [binarywang/WxJava#395]
```
wxMaService.getQrcodeService().createWxCodeLimit(idScene, null)
```
错误信息
```

me.chanjar.weixin.common.exception.WxErrorException: {"errcode":47001,"errmsg":"data format error hint: [Ox8o30679wxa6]"}
	at cn.binarywang.wx.miniapp.util.http.QrCodeRequestExecutor.execute(QrCodeRequestExecutor.java:52) ~[weixin-java-miniapp-2.9.0.jar:na]
	at cn.binarywang.wx.miniapp.util.http.QrCodeRequestExecutor.execute(QrCodeRequestExecutor.java:28) ~[weixin-java-miniapp-2.9.0.jar:na]
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:193) ~[weixin-java-miniapp-2.9.0.jar:na]
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:156) ~[weixin-java-miniapp-2.9.0.jar:na]
	at cn.binarywang.wx.miniapp.api.impl.WxMaQrcodeServiceImpl.createWxCodeLimit(WxMaQrcodeServiceImpl.java:64) ~[weixin-java-miniapp-2.9.0.jar:na]
	at cn.binarywang.wx.miniapp.api.impl.WxMaQrcodeServiceImpl.createWxCodeLimit(WxMaQrcodeServiceImpl.java:70) ~[weixin-java-miniapp-2.9.0.jar:na]
```

跟踪代码发现
```cn.binarywang.wx.miniapp.util.http.QrCodeRequestExecutor#execute 43行 ```
设置的entity 为 text/plan, 微信要求的请求是 application/json
```
httpPost.setEntity(new StringEntity(ticket.toString()));
```

**Comment by binarywang** [comment]
感谢提出此问题，但出错的原因不在于此，稍后准备修复一下

**Comment by charmingoh** [comment]
需要吧 WxMaWxcodeLimit 的 toString 函数去掉。

**Comment by binarywang** [comment]
2.9.2.BETA版本已修复
