### ISSUE TITLE
jodd工具版本兼容问题

### ISSUE THREAD

**Issue by iojh** [binarywang/WxJava#478]
`java.lang.NoSuchMethodError: jodd.io.ZipUtil.ungzip(Ljava/io/File;)Ljava/io/File;
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.handleGzipBill(BaseWxPayServiceImpl.java:444) ~[weixin-java-pay-2.9.6.BETA.jar:na]
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.downloadBill(BaseWxPayServiceImpl.java:418) ~[weixin-java-pay-2.9.6.BETA.jar:na]
	at com.github.binarywang.demo.wxpay.controller.WxPayController.downloadBill(WxPayController.java:409) ~[classes/:na]`

jodd 3.x版本 不支持该方法

**Comment by binarywang** [comment]
请仔细核对版本，本sdk使用的是3.7.1

**Comment by iojh** [comment]
thx,搞定了，用的是jodd,要用jodd-core,
