### ISSUE TITLE
XStreamTransformer.fromXml   Cannot construct type

### ISSUE THREAD

**Issue by lgb020** [binarywang/WxJava#488]
请问一下，我用了这个框架，某些时候会出现xml无法转成bean的情况。不知道是什么问题。
测试程序如下：
```
import me.chanjar.weixin.common.api.WxConsts;
import me.chanjar.weixin.mp.bean.message.WxMpXmlMessage;
import me.chanjar.weixin.mp.bean.message.WxMpXmlOutTextMessage;
import me.chanjar.weixin.mp.util.xml.XStreamTransformer;


public class Test {

	public static void main(String[] args) throws Exception {
		WxMpXmlOutTextMessage msg = new WxMpXmlOutTextMessage();
		msg.setContent("content");
		msg.setCreateTime(System.currentTimeMillis());
		msg.setFromUserName("fromUserName");
		msg.setMsgType(WxConsts.XmlMsgType.TEXT);
		msg.setToUserName("toUserName");
		String xml ="";
		xml = msg.toXml();
		System.out.println(xml);
		Thread.currentThread().sleep(100);
//		WxMpXmlOutTextMessage out = (WxMpXmlOutTextMessage) XStreamTransformer.fromXml(
//                WxMpUtil.getXmlOutMsgType(MessageUtil.parseMsgType(xml)), xml);
		WxMpXmlOutTextMessage msg2 = XStreamTransformer.fromXml(WxMpXmlOutTextMessage.class, xml);
		System.out.println("2:"+msg2.toString());
	}

}
```

运行输出的结果异常如下：
```
<xml>
  <ToUserName><![CDATA[toUserName]]></ToUserName>
  <FromUserName><![CDATA[fromUserName]]></FromUserName>
  <CreateTime>1520563913254</CreateTime>
  <MsgType><![CDATA[text]]></MsgType>
  <Content><![CDATA[content]]></Content>
</xml>
Exception in thread "main" com.thoughtworks.xstream.converters.ConversionException: Cannot construct type
---- Debugging information ----
message             : Cannot construct type
cause-exception     : java.lang.InstantiationException
cause-message       : me.chanjar.weixin.mp.bean.message.WxMpXmlOutMessage
construction-type   : me.chanjar.weixin.mp.bean.message.WxMpXmlOutMessage
class               : me.chanjar.weixin.mp.bean.message.WxMpXmlOutMessage
required-type       : me.chanjar.weixin.mp.bean.message.WxMpXmlOutMessage
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 1
version             : 1.4.9
-------------------------------
	at com.thoughtworks.xstream.converters.reflection.SunLimitedUnsafeReflectionProvider.newInstance(SunLimitedUnsafeReflectionProvider.java:86)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.instantiateNewInstance(AbstractReflectionConverter.java:584)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:280)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1076)
	at me.chanjar.weixin.mp.util.xml.XStreamTransformer.fromXml(XStreamTransformer.java:29)
	at com.fengjx.Test.main(Test.java:24)
Caused by: java.lang.InstantiationException: me.chanjar.weixin.mp.bean.message.WxMpXmlOutMessage
	at sun.misc.Unsafe.allocateInstance(Native Method)
	at com.thoughtworks.xstream.converters.reflection.SunLimitedUnsafeReflectionProvider.newInstance(SunLimitedUnsafeReflectionProvider.java:82)
	... 13 more
```

**Comment by binarywang** [comment]
仔细看了下，你是在用自己生成的xml，再解析回java bean，你这么做是出于什么考虑？
你自己在代码搜索下两个方法的使用场景，就知道你这么做其实是没有意义的。

**Comment by lgb020** [comment]
怎么说呢，就是我们现在有一个2年前的项目，他本来的设计就是把一些要回复的规则是组合成XML的（这些XML就是要被动回复给微信的XML。），也就是数据库里放的就是XML，我现在想要把这些存数据库一个字段里XML再转回对象，这样方便我接下来的操作；例如设置ToUserName,设置FromUserName等。请教一下XStreamTransformer.fromXml这个方法能实现吗？能实现的话要怎么写？还是说这个方法一定会去初始化一个父类的实例，而这个bean的父类是抽象类，所以无法这样做？

**Comment by binarywang** [comment]
只能这么说吧，这个方法本身是有局限性的，针对正常的使用场景是没有问题的。
但针对你的特殊需求，需要特殊处理，具体该怎么改造，自己调试下吧。
