### ISSUE TITLE
[Miniapp] checkUserInfo 用的解密算法不是 sha1Hex

### ISSUE THREAD

**Issue by blade254353074** [binarywang/WxJava#491]
https://mp.weixin.qq.com/debug/wxadoc/dev/api/signature.html

**Comment by blade254353074** [comment]
https://my.oschina.net/ngh8897/blog/411962

**Comment by binarywang** [comment]
楼主，没看懂你说什么，能否仔细描述下问题吗？
是你遇到了什么问题吗？或者说你改过什么代码后解决了这个问题？
总不能抛出来几个网址就完事了吧？

**Comment by blade254353074** [comment]
不好意思，刚刚在试，我也不会 Java，以为你看到网址就能直接明白 2333，查了下解决方案：

1. 添加包 `org.bouncycastle:bcprov-jdk15on:1.59`

在构造函数中为 Java Security 添加 Provider

```Java
Security.addProvider(new BouncyCastleProvider());
```
2. 解密方法中即可使用 AES/CBC/PKCS7Padding

```Java
Cipher.getInstance("AES/CBC/PKCS7Padding");
```

我随便实现了下，encryptedData 就可以顺利解密了：
```Java
package com.xxxx.finance.utils;

import me.chanjar.weixin.common.util.crypto.PKCS7Encoder;
import org.apache.commons.codec.binary.Base64;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.AlgorithmParameters;
import java.security.Security;

public class WxMaDecrypt {

    public WxMaDecrypt() {
        Security.addProvider(new BouncyCastleProvider());
    }

    public String exec(String sessionKey, String encryptedData, String ivStr) {
        try {
            String KEY_ALGORITHM = "AES";
            AlgorithmParameters params = AlgorithmParameters.getInstance(KEY_ALGORITHM);
            params.init(new IvParameterSpec(Base64.decodeBase64(ivStr)));

            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS7Padding");
            cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(Base64.decodeBase64(sessionKey), KEY_ALGORITHM), params);

            return new String(PKCS7Encoder.decode(cipher.doFinal(Base64.decodeBase64(encryptedData))), StandardCharsets.UTF_8);
        } catch (Exception e) {
            throw new RuntimeException("AES解密失败", e);
        }
    }

}
```

**Comment by blade254353074** [comment]
如果不加这个套件，WxMaCryptUtils 中的 decrypt 方法会报错

**Comment by binarywang** [comment]
请问报错信息是什么？这个我最初在做的时候是没问题的，里面的单元测试现在运行都没问题，不知道你遇到的问题是怎么出现的？

**Comment by blade254353074** [comment]
。。。今天再测试发现不报错了

**Comment by blade254353074** [comment]
我找了下昨天的 log

```log
03.11 19:50:53 [ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $] with root cause
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[gson-2.8.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.1.jar:?]
	at cn.binarywang.wx.miniapp.bean.WxMaUserInfo.fromJson(WxMaUserInfo.java:27) ~[weixin-java-miniapp-2.9.0.jar:?]
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getUserInfo(WxMaUserServiceImpl.java:41) ~[weixin-java-miniapp-2.9.0.jar:?]
	at com.xxxx.finance.controller.wx.WxMaUserController.info(WxMaUserController.java:86) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
...
```

报错发生在这句：
```Java
@Override
public WxMaUserInfo getUserInfo(String sessionKey, String encryptedData, String ivStr) {
  return WxMaUserInfo.fromJson(WxMaCryptUtils.decrypt(sessionKey, encryptedData, ivStr));
}
```

当时 debug 的时候，`WxMaCryptUtils.decrypt(sessionKey, encryptedData, ivStr)` 返回的是一串乱码，所以 json 转换报错了？

**Comment by binarywang** [comment]
最好是你重现问题后再来调试跟踪下吧，找出问题真正的根源。
另外即使有问题，那报错的地方也与你标题所指的方法checkUserInfo无关吧？

**Comment by blade254353074** [comment]
嗯 我先关了，有问题再说

**Comment by sunhai1988** [comment]
`    // 用户信息校验
        if (!wxMaService.getUserService().checkUserInfo(sessionKey, rawData, signature)) {
            return Result.error("获取错误");
        }`

`  @Override
  public boolean checkUserInfo(String sessionKey, String rawData, String signature) {
    final String generatedSignature = DigestUtils.sha1Hex(rawData + sessionKey);
    return generatedSignature.equals(signature);
  }`

mini 3.3.0  
 org.apache.commons.codec  1.10 
验证checkUserInfo  总是不对！！！

**Comment by binarywang** [comment]
> ` // 用户信息校验 if (!wxMaService.getUserService().checkUserInfo(sessionKey, rawData, signature)) { return Result.error("获取错误"); }`
> 
> ` @Override public boolean checkUserInfo(String sessionKey, String rawData, String signature) { final String generatedSignature = DigestUtils.sha1Hex(rawData + sessionKey); return generatedSignature.equals(signature); }`
> 
> mini 3.3.0
> org.apache.commons.codec 1.10
> 验证checkUserInfo 总是不对！！！

有问题请新开issue，不要在已关闭的issue里面追问不相关问题，谢谢。
