### ISSUE TITLE
NoSuchMethodError-------StringUtils.isAnyEmpty

### ISSUE THREAD

**Issue by ymsmile** [binarywang/WxJava#499]
我使用的是weixin-java-open的2.9.8.BETA版本

`Caused by: java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.isAnyEmpty([Ljava/lang/CharSequence;)Z
        at me.chanjar.weixin.common.util.crypto.SHA1.gen(SHA1.java:17)
        at me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl.checkSignature(WxOpenComponentServiceImpl.java:88)
        at www.aaa.com.wechat.WechatNotifyController.receiveTicket(WechatNotifyController.java:50)`

StringUtils类都没有isAnyEmpty方法

**Comment by ymsmile** [comment]
已解决，是我的commons-lang3包版本过低，改为3.5即可。

参考：https://raw.githubusercontent.com/wechat-group/weixin-java-tools/master/pom.xml
