### ISSUE TITLE
开放平台小程序登录时报错

### ISSUE THREAD

**Issue by TonyLuo** [binarywang/WxJava#512]
WxMaJscode2SessionResult session = openService.getWxOpenComponentService().getWxMaServiceByAppid(authorizerAppId).getUserService()
            .getSessionInfo(code);

```
internal Server Error

java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at com.google.common.base.Joiner.toString(Joiner.java:454)
	at com.google.common.base.Joiner$MapJoiner.appendTo(Joiner.java:385)
	at com.google.common.base.Joiner$MapJoiner.appendTo(Joiner.java:415)
	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:441)
	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:430)
	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:348)
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getSessionInfo(WxMaUserServiceImpl.java:35)
```

**Comment by 007gzs** [comment]
确认是bug，我周一改下

**Comment by TonyLuo** [comment]
另外想请教下开放平台的问题，wx.login只能拿到code，在小程序页面上怎么可以获取authorizerAppId？如果登录时只传code，没有authorizerAppId的话，后台怎么辨别登录请求到底是哪个授权的小程序发起的呢？目前我是在后台hardcode写死了authorizerAppId，这样没办法一个小程序模板支持多个不同的授权的小程序

**Comment by 007gzs** [comment]
域名是以authorizerAppId开头的，从host里取，公众号是这样的，小程序我没弄过应该也是一样

**Comment by 007gzs** [comment]
bug我改了，提交了pr，你如果会用源码本地编译的话可以测下

**Comment by TonyLuo** [comment]
谢谢

**Comment by TonyLuo** [comment]
今天看了下maven库，上面还没有发布这个hotfix。能否发布下这个hotfix呢？ @binarywang

**Comment by binarywang** [comment]
过几天准备发布正式版，不好意思，请稍微等待几天
