### ISSUE TITLE
spring mvc使用weixin-java-miniapp 提示No qualifying bean of type [cn.binarywang.wx.miniapp.api.WxMaService]

### ISSUE THREAD

**Issue by fendo8888** [binarywang/WxJava#582]
把weixin-java-miniapp-demo中的WxPortalController 复制到自己的spring mvc项目中一运行就报错:
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [cn.binarywang.wx.miniapp.api.WxMaService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1301)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1047)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 67 more

提示WxMaService错误，估计是没有被扫描到。。

**Comment by binarywang** [comment]
你不会设置一下吗？参考下demo是如何做的

**Comment by fendo8888** [comment]
在spring-content配置文件中加入
	<context:component-scan base-package="cn.binarywang.wx.miniapp"></context:component-scan>

还是报错。。

**Comment by fendo8888** [comment]
后面发现你是在WxMaConfiguration.jar中配置的，在spring mvc中如何使用，有没有demo

**Comment by binarywang** [comment]
不管是spring boot，还是spring mvc，都可以使用这种方式配置，楼主可以再去温习下spring基础吧
