### ISSUE TITLE
解密消息出错

### ISSUE THREAD

**Issue by liuzhihai520** [binarywang/WxJava#622]
在解密微信推送信息时：
WxMpXmlMessage inMessage = WxMpXmlMessage.fromEncryptedXml(requestBody, wxMpService.getWxMpConfigStorage(), timestamp, nonce, msgSignature);

报错如下：
java.lang.RuntimeException: java.lang.IllegalArgumentException: 1611744036 > 320
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:270) ~[weixin-java-common-2.9.0.jar:na]
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:227) ~[weixin-java-common-2.9.0.jar:na]
	at me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromEncryptedXml(WxMpXmlMessage.java:452) ~[weixin-java-mp-2.9.0.jar:na]
	at com.book.web.contoller.WxBaseController.post(WxBaseController.java:87) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]

**Comment by binarywang** [comment]
相关参数是否配置正确，先用demo配置完跑下看看。

**Comment by liuzhihai520** [comment]
我试了一下，本地正确，服务器才出这个错，奇怪了。

**Comment by liuzhihai520** [comment]
我试了一下，本地正确，服务器才出这个错，奇怪了。

**Comment by binlibinli** [comment]
我也有类似的异常：exception：java.lang.RuntimeException: java.lang.IllegalArgumentException: 20 > -604338658
SEVERE: Servlet.service() for servlet [default] in context with path [] threw exception
java.lang.RuntimeException: java.lang.IllegalArgumentException: 20 > -604338658
at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:270)
at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:227)
at me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromEncryptedXml(WxMpXmlMessage.java:449)
at me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromEncryptedXml(WxMpXmlMessage.java:458)
at net.goshare.weixin.mp.pub.WeiXinJoinFilter.doFilter(WeiXinJoinFilter.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:67)
at com.sun.proxy.$Proxy430.doFilter(Unknown Source)
at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:204)
at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:109)
at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:119)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 20 > -604338658
at java.util.Arrays.copyOfRange(Arrays.java:3519)
at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:265)

**Comment by binlibinli** [comment]
Caused by: java.lang.IllegalArgumentException: 20 > -604338658
at **java.util.Arrays.copyOfRange(Arrays.java:3519)**
at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:265)
这里出的异常，但不知道是什么原因啊？
      xmlContent = new String(Arrays.copyOfRange(bytes, 20, 20 + xmlLength),
        CHARSET);
有碰到这个问题的兄弟吗？如何解决？

**Comment by binarywang** [comment]
很有可能是部分参数配置有问题，请先仔细核实下

**Comment by binlibinli** [comment]
谢谢，确实是参数配置问题，消息加解密密钥(EncodingAESKey)不知何时被重置过了，配置里没有更新导致的，谢谢一语道破

**Comment by Mrtanglei** [comment]
@binarywang  他这个是EncodingAESKey密匙更改了，我这边对照了下，密匙是对的

**Comment by liuzhihai520** [comment]
@Mrtanglei 这个问题,我之前遇到过两次，都是参数问题导致的。你可以详细打印对比一下你的参数。
