### ISSUE TITLE
沙箱环境回调使用WxPayOrderNotifyResult解析xml报错

### ISSUE THREAD

**Issue by yunexuan** [binarywang/WxJava#629]
```
com.thoughtworks.xstream.converters.ConversionException: Index: 1, Size: 0 : Index: 1, Size: 0
---- Debugging information ----
message             : Index: 1, Size: 0
cause-exception     : java.lang.IndexOutOfBoundsException
cause-message       : Index: 1, Size: 0
class               : com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyResult
required-type       : com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyResult
converter-type      : com.github.binarywang.wxpay.converter.WxPayOrderNotifyResultConverter
line number         : 14
version             : 1.4.7
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1040)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1031)
	at com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyResult.fromXML(WxPayOrderNotifyResult.java:278)
	at com.youren.mall.pay.controller.PayController.notify(PayController.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at com.github.binarywang.wxpay.converter.WxPayOrderNotifyResultConverter.getIndex(WxPayOrderNotifyResultConverter.java:125)
	at com.github.binarywang.wxpay.converter.WxPayOrderNotifyResultConverter.unmarshal(WxPayOrderNotifyResultConverter.java:83)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 49 more

```

**Comment by binarywang** [comment]
请仔细看下回调具体内容，是不是什么东西缺失？

**Comment by yunexuan** [comment]
这是沙箱环境回调回来的内容，用WxPayOrderNotifyResult.fromXml去解析会报错
`<xml>
  <openid><![CDATA[sandboxopenid]]></openid>
  <trade_type><![CDATA[NATIVE]]></trade_type>
  <coupon_fee><![CDATA[3]]></coupon_fee>
  <cash_fee_type><![CDATA[CNY]]></cash_fee_type>
  <nonce_str><![CDATA[1529028826646]]></nonce_str>
  <time_end><![CDATA[20180615101350]]></time_end>
  <err_code_des><![CDATA[SUCCESS]]></err_code_des>
  <return_code><![CDATA[SUCCESS]]></return_code>
  <mch_id><![CDATA[1417006965]]></mch_id>
  <settlement_total_fee><![CDATA[100]]></settlement_total_fee>
  <sign><![CDATA[21D461618FF06278FC0EA14A940D7D1F]]></sign>
  <cash_fee><![CDATA[99]]></cash_fee>
  <coupon_id_1><![CDATA[67890]]></coupon_id_1>
  <coupon_type_0><![CDATA[CASH]]></coupon_type_0>
  <coupon_id_0><![CDATA[123456]]></coupon_id_0>
  <coupon_fee_0><![CDATA[1]]></coupon_fee_0>
  <coupon_fee_1><![CDATA[2]]></coupon_fee_1>
  <is_subscribe><![CDATA[Y]]></is_subscribe>
  <return_msg><![CDATA[OK]]></return_msg>
  <fee_type><![CDATA[CNY]]></fee_type>
  <bank_type><![CDATA[CMC]]></bank_type>
  <attach><![CDATA[sandbox_attach]]></attach>
  <device_info><![CDATA[]]></device_info>
  <out_trade_no><![CDATA[afadsfadsf]]></out_trade_no>
  <coupon_type_1><![CDATA[NO_CASH]]></coupon_type_1>
  <result_code><![CDATA[SUCCESS]]></result_code>
  <total_fee><![CDATA[102]]></total_fee>
  <appid><![CDATA[wx9615b4d55c15236c]]></appid>
  <coupon_count><![CDATA[2]]></coupon_count>
  <transaction_id><![CDATA[4895293615520845289541350836627]]></transaction_id>
  <err_code><![CDATA[SUCCESS]]></err_code>
</xml>
`

**Comment by binarywang** [comment]
调试了下，是这个沙箱环境返回的模拟数据没有按常理出牌，导致解析程序出问题。你可以暂时不予理会，直接用正式环境试试，这个代码已经存在很久了，不会有问题了。
稍后我在想办法让代码做个兼容，兼容这种变态的模拟数据。
