### ISSUE TITLE
小程序获取用户信息报异常JsonSyntaxException

### ISSUE THREAD

**Issue by AbeGangh** [binarywang/WxJava#652]
`  String sessionKey = session.getSessionKey();
        WxMaUserInfo userInfo = wxService.getUserService().getUserInfo(sessionKey, wechatUserLoginVM.getEncryptedData(), wechatUserLoginVM.getIv());`

  ### ### 
error:   
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at cn.binarywang.wx.miniapp.bean.WxMaUserInfo.fromJson(WxMaUserInfo.java:27)
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getUserInfo(WxMaUserServiceImpl.java:30)

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/issues/359 先参考下这个

**Comment by AbeGangh** [comment]
感谢！
