### ISSUE TITLE
获取用户手机号码提示 Input length not multiple of 16 bytes

### ISSUE THREAD

**Issue by alexnest** [binarywang/WxJava#666]
调用 cn.binarywang.wx.miniapp.util.crypt 这个类 decrypt 这个方法的时候报以下错误。相关的main方法和报错如下
`

    String sessionKey = "IBd/IJsXb71Mn4EGUbk4FA==";
    String encryptedData = "SoMlHIchlE03nBR c2FSwJKI8v/cOpON1Bf/lzxRu kLZpwOOUhMDss0WtFFKZ EIDkt1/oLz7KqiqxFCPBdksiMEQQuB/ZVDbnXKRDSYldLb5fZItJVX0dLSOs2rPIebW2RqNmeiSV/RFC2Gy8Rt4SLS3lOz1VtOOBfQX1XA3ke9cUV3xP60p1HjEhlptTbIfSNSi4lmDY5vKf7Hcc51w==";
    String ivStr = "vGDfrGx5uLY4m1CDFFaCKw==";
    System.out.println(decrypt(sessionKey,encryptedData,ivStr));
`

Exception in thread "main" java.lang.RuntimeException: AES解密失败
	at cn.binarywang.wx.miniapp.util.crypt.WxMaCryptUtils.decrypt(WxMaCryptUtils.java:46)
	at cn.binarywang.wx.miniapp.util.crypt.WxMaCryptUtils.main(WxMaCryptUtils.java:56)
Caused by: javax.crypto.IllegalBlockSizeException: Input length not multiple of 16 bytes
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1041)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:985)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at cn.binarywang.wx.miniapp.util.crypt.WxMaCryptUtils.decrypt(WxMaCryptUtils.java:44)
	... 1 more

**Comment by alexnest** [comment]
不好意思，打扰了。原因是 sessionKey ， encryptedData ， ivStr 这三个参数要 encodeURIComponent处理下，java代码里要像下面这样处理下
        sessionKey = URLDecoder.decode(sessionKey,"UTF-8");
        encryptedData = URLDecoder.decode(encryptedData,"UTF-8");
        iv = URLDecoder.decode(iv,"UTF-8");
