### ISSUE TITLE
WxPayRefundResult 存在空指针的情况

### ISSUE THREAD

**Issue by mitolH** [binarywang/WxJava#696]
https://github.com/Wechat-Group/weixin-java-tools/blob/bab396cb0436f35a133d7c7166af9ee50453b484/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/result/WxPayRefundResult.java#L111

java.lang.NullPointerException
	at com.github.binarywang.wxpay.bean.result.WxPayRefundResult.composeRefundCoupons(WxPayRefundResult.java:111)
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.refund(BaseWxPayServiceImpl.java:94)
	at com.youxuan.oms.business.service.payment.impl.WechatPayServiceImpl.refundOrder(WechatPayServiceImpl.java:170)
	at com.youxuan.oms.business.service.payment.impl.WechatPayServiceImpl$$FastClassBySpringCGLIB$$668c425d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.youxuan.oms.business.service.payment.impl.WechatPayServiceImpl$$EnhancerBySpringCGLIB$$6664c3f7.refundOrder(<generated>)
	at com.youxuan.oms.business.service.payment.impl.PaymentServiceImpl.refundOrder(PaymentServiceImpl.java:178)
	at com.youxuan.oms.business.service.payment.impl.PaymentServiceImpl$$FastClassBySpringCGLIB$$d8e42ff9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

具体的错误异常如上，是在重复运行申请退款的用例的时候出现的。

**Comment by mitolH** [comment]
经确认在develop分支已修复。因此关闭

https://github.com/Wechat-Group/weixin-java-tools/blob/c237bb81dd5bddd67abc83259ff82fe797c7d4de/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/result/WxPayRefundResult.java#L125
