### ISSUE TITLE
微信退款空指针问题（基本账户余额不足，请充值后重新发起）

### ISSUE THREAD

**Issue by huxudong** [binarywang/WxJava#716]
2018-08-17T03:28:59.383105000Z 【响应数据】：<xml><return_code><![CDATA[SUCCESS]]></return_code>
2018-08-17T03:28:59.384909000Z <return_msg><![CDATA[OK]]></return_msg>
2018-08-17T03:28:59.385902000Z <appid><![CDATA[xxx]]></appid>
2018-08-17T03:28:59.387528000Z <mch_id><![CDATA[xxx]]></mch_id>
2018-08-17T03:28:59.388717000Z <nonce_str><![CDATA[BuQM1pRGlwDOoT0l]]></nonce_str>
2018-08-17T03:28:59.389614000Z <sign><![CDATA[F40595CC160A1AD287F5D288BA1E92BD]]></sign>
2018-08-17T03:28:59.391003000Z <result_code><![CDATA[FAIL]]></result_code>
2018-08-17T03:28:59.392485000Z <err_code><![CDATA[NOTENOUGH]]></err_code>
2018-08-17T03:28:59.393177000Z <err_code_des><![CDATA[基本账户余额不足，请充值后重新发起]]></err_code_des>
2018-08-17T03:28:59.394124000Z </xml>
2018-08-17T03:28:59.411212000Z java.lang.NullPointerException
2018-08-17T03:28:59.415006000Z 	at com.github.binarywang.wxpay.bean.result.WxPayRefundResult.composeRefundCoupons(WxPayRefundResult.java:111)
2018-08-17T03:28:59.415322000Z 	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.refund(BaseWxPayServiceImpl.java:94)
2018-08-17T03:28:59.415618000Z 	at 

com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl-->refund()
com.github.binarywang.wxpay.bean.result.WxPayRefundResult--->composeRefundCoupons()

/**
   * 组装生成退款代金券信息.
   */
  public void composeRefundCoupons() {
    List<WxPayRefundCouponInfo> coupons = Lists.newArrayList();
    for (int i = 0; i < this.getCouponRefundCount(); i++) {
      coupons.add(
        new WxPayRefundCouponInfo(
          this.getXmlValue("xml/coupon_refund_id_" + i),
          this.getXmlValueAsInt("xml/coupon_refund_fee_" + i),
          this.getXmlValue("xml/coupon_type_" + i)
        )
      );
    }
    this.setRefundCoupons(coupons);
  }

this.getCouponRefundCount()---->>引起空指针

**Comment by huadahuang1983** [comment]
这个新版本已经修正了

**Comment by huxudong** [comment]
哦我用的3.10

**Comment by binarywang** [comment]
用最新测试版
