### ISSUE TITLE
关于小程序用户登录，根据code换取用户信息bug(紧急)

### ISSUE THREAD

**Issue by xjar-s** [binarywang/WxJava#774]
小程序根据前台传过来的code,通过：
 **WxMaJscode2SessionResult session = this.wxService.getUserService().getSessionInfo(code);**
换取的时候，报了如下错误：
26-Sep-2018 19:44:32.722 严重 [http-nio-8085-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [springServlet] in context with path [/nsjc-charge] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.replaceAll(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;] with root cause
 java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.replaceAll(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at me.chanjar.weixin.common.util.DataUtils.handleDataWithSecret(DataUtils.java:20)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:234)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:205)
	at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.get(WxMaServiceImpl.java:189)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1437)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by binarywang** [comment]
大哥，别急，你这是jar版本问题，换个版本就行了

**Comment by xjar-s** [comment]
> 大哥，别急，你这是jar版本问题，换个版本就行了

我从1.7 换成了1.8 也是不行的呢

**Comment by xjar-s** [comment]
我从1.7换成了1.8还是不行的哦


| |
xresponsibility
邮箱：xresponsibility@126.com
|

Signature is customized by Netease Mail Master

在2018年09月26日 20:34，Binary Wang 写道：

大哥，别急，你这是jar版本问题，换个版本就行了

**Comment by binarywang** [comment]
我说的是你提示找不到方法的那个类对应的jar包的版本，跟jdk版本没关系

**Comment by binarywang** [comment]
也就是commons-lang3

**Comment by xjar-s** [comment]
请问是用什么jar包呢 麻烦帮帮忙解释一下




| |
xresponsibility
邮箱：xresponsibility@126.com
|

Signature is customized by Netease Mail Master

在2018年09月26日 20:46，Binary Wang 写道：

我说的是你提示找不到方法的那个类对应的jar包的版本，跟jdk版本没关系

**Comment by xjar-s** [comment]
请问下它最低需要什么版本呢 我检查下这边的依赖




| |
xresponsibility
邮箱：xresponsibility@126.com
|

Signature is customized by Netease Mail Master

在2018年09月26日 20:49，Binary Wang 写道：

也就是commons-lang3

**Comment by binarywang** [comment]
你看pom文件就知道了，目前是3.5

**Comment by xjar-s** [comment]
好的 万分感谢大佬




| |
xresponsibility
邮箱：xresponsibility@126.com
|

Signature is customized by Netease Mail Master

在2018年09月26日 20:52，Binary Wang 写道：

你看pom文件就知道了，目前是3.5
