### ISSUE TITLE
有一个报错始终找不到原因，环境 springboot 1.5.16.RELEASE  springcloud Dalston.SR5

### ISSUE THREAD

**Issue by fufenghua** [binarywang/WxJava#805]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wx.mp-cn.enjoylife.service.consumer.configurer.WxMpProperties': Could not bind properties to WxMpProperties (prefix=wx.mp, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is java.lang.NullPointerException
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:336) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:292) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:105) ~[spring-cloud-context-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:90) ~[spring-cloud-context-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:138) ~[spring-cloud-context-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:51) ~[spring-cloud-context-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration.afterSingletonsInstantiated(ConfigurationPropertiesRebinderAutoConfiguration.java:79) ~[spring-cloud-context-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781) ~[spring-beans-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at cn.enjoylife.service.consumer.ServiceConsumerApplication.main(ServiceConsumerApplication.java:19) [classes/:na]
Caused by: java.lang.NullPointerException: null
	at org.springframework.boot.bind.RelaxedDataBinder.extendCollectionIfNecessary(RelaxedDataBinder.java:349) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.bind.RelaxedDataBinder.initializePath(RelaxedDataBinder.java:299) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.bind.RelaxedDataBinder.normalizePath(RelaxedDataBinder.java:268) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.bind.RelaxedDataBinder.modifyProperty(RelaxedDataBinder.java:249) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.bind.RelaxedDataBinder.modifyProperties(RelaxedDataBinder.java:164) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:137) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.validation.DataBinder.bind(DataBinder.java:741) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:287) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:250) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:331) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	... 21 common frames omitted

**Comment by fufenghua** [comment]
debug发现是因为有两次WxMpProperties 被绑定了两次，第一次读到数据，第二次没有，导致报错。但是为什么会被bind两次，实在找不到原因，最后退而求其次将其改造为springmvc的注册方式，因为本来项目是springcloud的，所以用的springboot的模版，因为这个问题，我只好改成springmvc的注册方式了0.0

**Comment by binarywang** [comment]
也没有具体代码，无法定位问题。另外跟本sdk无关，先关闭。
