### ISSUE TITLE
企业打款解析xml出错

### ISSUE THREAD

**Issue by hewenhao123** [binarywang/WxJava#810]
com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:126) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1076) ~[xstream-1.4.9.jar!/:1.4.9]
	at com.github.binarywang.wxpay.bean.result.BaseWxPayResult.fromXML(BaseWxPayResult.java:136) ~[weixin-java-pay-3.2.0.jar!/:na]
	at com.github.binarywang.wxpay.service.impl.EntPayServiceImpl.entPay(EntPayServiceImpl.java:58) ~[weixin-java-pay-3.2.0.jar!/:na]
Caused by: java.io.EOFException: input contained no data
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003) ~[xpp3_min-1.1.4c.jar!/:na]
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046) ~[xpp3_min-1.1.4c.jar!/:na]
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410) ~[xpp3_min-1.1.4c.jar!/:na]
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395) ~[xpp3_min-1.1.4c.jar!/:na]
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093) ~[xpp3_min-1.1.4c.jar!/:na]
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109) ~[xstream-1.4.9.jar!/:1.4.9]
	... 101 common frames omitted

**Comment by binarywang** [comment]
你这个错误很明显` java.io.EOFException: input contained no data`

**Comment by binarywang** [comment]
你这个错误很明显 `java.io.EOFException: input contained no data`

（此条为再次回复的，很显然，github上午发生故障，导致数据丢失）
