### ISSUE TITLE
小程序用户信息AES解密失败

### ISSUE THREAD

**Issue by sophia0909** [binarywang/WxJava#843]
ava.lang.RuntimeException: AES解密失败
	at cn.binarywang.wx.miniapp.util.crypt.WxMaCryptUtils.decrypt(WxMaCryptUtils.java:39)
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getUserInfo(WxMaUserServiceImpl.java:30)

Caused by: javax.crypto.IllegalBlockSizeException: Input length not multiple of 16 bytes
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1042)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:985)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at cn.binarywang.wx.miniapp.util.crypt.WxMaCryptUtils.decrypt(WxMaCryptUtils.java:37)
	... 83 more

求大佬解决。不知道怎么放图很抱歉。

**Comment by binarywang** [comment]
重复
