### ISSUE TITLE
XStream在maven依赖中有，但依然包找不到类

### ISSUE THREAD

**Issue by brett25** [binarywang/WxJava#91]
项目正常运行起来后，在消息转换时报XStreamTransformer类不存在，可MAVN依赖中存在该JAR包。
我百度说SAE已经禁用了XSteam.而我在本地tomcat7中也遇到同样的问题，这个该如何解决是好？
（http://blog.csdn.net/lyq8479/article/details/38878543）
Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.chanjar.weixin.mp.util.xml.XStreamTransformer
	at me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromXml(WxMpXmlMessage.java:545)
	at com.bhj.controller.CoreWxController.wechatCore(CoreWxController.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

![image](https://cloud.githubusercontent.com/assets/14285848/21004982/01d5be2e-bd6e-11e6-83e9-858ec4c36fde.png)

**Comment by binarywang** [comment]
你要找的这个类 me.chanjar.weixin.mp.util.xml.XStreamTransformer 并不是在你图片中所指示的jar包中

**Comment by binarywang** [comment]
按照你所给链接中所示解决方法，你可能需要自己替换xstream的包

**Comment by aimilin6688** [comment]
版本太低，自己指定使用版本就可以了！

**Comment by binarywang** [comment]
@brett25 
楼主问题解决了吗？

**Comment by cloudAndMonkey** [comment]
我遇到同样的问题，xtream 升级到1.4.8

**Comment by binarywang** [comment]
目前项目里用到的是1.4.7。

**Comment by binarywang** [comment]
先关闭掉了，总是有人发完问题就再也不回头关注了，这是为什么呢？

**Comment by fengqiangboy** [comment]
我刚才也遇到了，添加下面的依赖解决

```
compile group: 'com.thoughtworks.xstream', name: 'xstream', version: '1.4.11.1'
```

**Comment by binarywang** [comment]
问题很简单，即版本的问题

**Comment by Horizon1123** [comment]
我升级了，但是也没有用呢从1.4.8 升到1.4.11.1
