### ISSUE TITLE
卡片激活方式为自动激活，拉取用户信息时报错

### ISSUE THREAD

**Issue by gaols** [binarywang/WxJava#928]
java.lang.NullPointerException: null
      at me.chanjar.weixin.mp.util.json.WxMpMemberCardUserInfoResultGsonAdapter.deserialize(WxMpMemberCardUserInfoResultGsonAdapter.java:39) ~[weixin-java-mp-3.2.0.jar:na]
      at me.chanjar.weixin.mp.util.json.WxMpMemberCardUserInfoResultGsonAdapter.deserialize(WxMpMemberCardUserInfoResultGsonAdapter.java:17) ~[weixin-java-mp-3.2.0.jar:na]
      at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[gson-2.3.jar:na]
      at com.google.gson.Gson.fromJson(Gson.java:805) ~[gson-2.3.jar:na]
      at com.google.gson.Gson.fromJson(Gson.java:870) ~[gson-2.3.jar:na]
      at me.chanjar.weixin.mp.api.impl.WxMpMemberCardServiceImpl.getUserInfo(WxMpMemberCardServiceImpl.java:242) ~[weixin-java-mp-3.2.0.jar:na]
      at com.sf.wxweb.card.handler.UserGetCardHandler.getCustomerInfo(UserGetCardHandler.java:94) ~[classes/:na]
      at com.sf.wxweb.card.handler.UserGetCardHandler.access$300(UserGetCardHandler.java:26) ~[classes/:na]
      at com.sf.wxweb.card.handler.UserGetCardHandler$1.run(UserGetCardHandler.java:61) ~[classes/:na]
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
      at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
      at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

调用的方法为：

    wxMpService.getMemberCardService().getUserInfo(cardId, code);

**Comment by binarywang** [comment]
你的接口请求响应报文是什么？麻烦发一下看看

**Comment by gaols** [comment]
{
      "errcode": 0,
      "errmsg": "ok",
      "openid": "oVEy8wtbq1XbcccWjU86WCFnu-d4",
      "nickname": "小小风云",
      "membership_number": "295013199811",
      "sex": "UNKNOW",
      "user_card_status": "NORMAL",
      "has_active": true
    }

微信接口：https://api.weixin.qq.com/card/membercard/userinfo/get?access_token=

**Comment by binarywang** [comment]
没有user_info，确实是个问题，可以修复下。

**Comment by binarywang** [comment]
3.3.4.B 测试版本已修复
