### ISSUE TITLE
WxMpService循环依赖

### ISSUE THREAD

**Issue by Ja1-Lin** [binarywang/WxJava#934]
### 问题描述：

> 偶尔启动容器时会报循环依赖的错误。具体异常和相关类代码如下。

### 异常堆栈信息
`
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'TestController': Unsatisfied dependency expressed through field 'wxMpService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'wxMpConfig': Unsatisfied dependency expressed through field 'unsubscribeHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'unsubscribeHandler': Unsatisfied dependency expressed through field 'memberService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memberService': Unsatisfied dependency expressed through field 'wxMpService'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'wxMpService': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.renren.RenrenApplication.main(RenrenApplication.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
`

### 相关类的代码
**wxMpConfig**
`
@Configuration
@EnableConfigurationProperties(WxProperties.class)
public class WxMpConfig {

    @Autowired
    private UnsubscribeHandler unsubscribeHandler;

    @Autowired
    private WxMessageInRedisDuplicateChecker redisDuplicateChecker;

    @Bean
    public WxMpConfigStorage configStorage() {
        WxMpInRedisConfigStorage storage = new WxMpInRedisConfigStorage();
        storage.setAppId(this.properties.getAppId());
        storage.setSecret(this.properties.getSecret());
        storage.setToken(this.properties.getToken());
        storage.setAesKey(this.properties.getAesKey());
        return storage;
    }

    @Bean
    public WxMpService wxMpService(WxMpConfigStorage configStorage) {
        WxMpService wxMpService = new me.chanjar.weixin.mp.api.impl.WxMpServiceImpl();
        wxMpService.setWxMpConfigStorage(configStorage);
        return wxMpService;
    }

    @Bean
    public WxMpMessageRouter router(WxMpService wxMpService) {
        WxMpMessageRouter newRouter = new WxMpMessageRouter(wxMpService);

        // 取消关注事件
        newRouter.rule().async(false).msgType(XmlMsgType.EVENT)
                .event(EventType.UNSUBSCRIBE)
                .handler(this.unsubscribeHandler).end();

        return newRouter;
    }
}
`

**UnsubscribeHandler**
`
@Component
public class UnsubscribeHandler extends AbstractHandler {

    @Autowried
    MemberService memberService

    @Override
    public WxMpXmlOutMessage handle(WxMpXmlMessage wxMessage,
                                    Map<String, Object> context, WxMpService wxMpService,
                                    WxSessionManager sessionManager) {
        //...
        return null;
    }
}
`

**MemberService**
`
@Service("memberService")
public class MemberServiceImpl extends BasicServiceImpl<MemberDao, Member> implements MemberService {

    @Autowired
    private WxMpService wxMpService;
`

**Comment by binarywang** [comment]
你这循环依赖的很明显了吧，重构代码吧，别这么搞

**Comment by Ja1-Lin** [comment]
> 你这循环依赖的很明显了吧，重构代码吧，别这么搞

可是spring解决了属性注入循环依赖的问题。但我也没发现有构造注入地方。

**Comment by binarywang** [comment]
仔细再检查下，不行就调试看看

**Comment by einsitang** [comment]
WxMpConfig 需要注入 UnsubscribeHandler
UnsubscribeHandler 需要注入  MemberService
MemberService 需要注入  WxMpService
WxMpService 需要 WxMpConfigStorage
WxMpConfigStorage 需要  WxMpConfig 
？？？ 没看到吗？

**Comment by Ja1-Lin** [comment]
> WxMpConfig 需要注入 UnsubscribeHandler
> UnsubscribeHandler 需要注入 MemberService
> MemberService 需要注入 WxMpService
> WxMpService 需要 WxMpConfigStorage
> WxMpConfigStorage 需要 WxMpConfig
> ？？？ 没看到吗？

spring不是解决了循环**注入**的依赖？,所以不会存在循环依赖，除非是构造依赖。不知道我有没有理解错

**Comment by binarywang** [comment]
你不是在使用spring吗？强烈建议不要产生循环依赖，即使你的程序能跑起来，这样的程序也是有极大隐患的。

**Comment by felix9ia** [comment]
@Ja1-Lin 最终咋解决了?重构了?
