### ISSUE TITLE
微信公众号支付统一下单方法报错

### ISSUE THREAD

**Issue by crazymaker** [binarywang/WxJava#937]
Caused by: java.lang.NoSuchMethodError: com.thoughtworks.xstream.XStream.setupDefaultSecurity(Lcom/thoughtworks/xstream/XStream;)V
at me.chanjar.weixin.common.util.xml.XStreamInitializer.getInstance(XStreamInitializer.java:47)
at com.github.binarywang.wxpay.bean.request.BaseWxPayRequest.toXML(BaseWxPayRequest.java:189)
at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.unifiedOrder(BaseWxPayServiceImpl.java:387)
at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.createOrder(BaseWxPayServiceImpl.java:302)
at com.jeeplus.modules.wx.web.WeixinController.pay(WeixinController.java:172)

**Comment by crazymaker** [comment]
已找到问题 xstream版本太低 重新更换最新版本的就解决了
