### ISSUE TITLE
获取component_verify_ticket后，解密异常

### ISSUE THREAD

**Issue by briefguo** [binarywang/WxJava#958]
Hello,

我在使用，开发平台模块的Demo时，微信推完component_verify_ticket后，解密过程遇到这样的问题

```shell
Resolving exception from handler [public java.lang.Object com.github.binarywang.demo.wx.open.controller.WechatNotifyController.receiveTicket(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]: java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
2019-03-02 22:10:12.532 DEBUG 25026 --- [nio-3888-exec-1] .w.s.m.a.ResponseStatusExceptionResolver : Resolving exception from handler [public java.lang.Object com.github.binarywang.demo.wx.open.controller.WechatNotifyController.receiveTicket(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]: java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
2019-03-02 22:10:12.533 DEBUG 25026 --- [nio-3888-exec-1] .w.s.m.s.DefaultHandlerExceptionResolver : Resolving exception from handler [public java.lang.Object com.github.binarywang.demo.wx.open.controller.WechatNotifyController.receiveTicket(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]: java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
2019-03-02 22:10:12.555 DEBUG 25026 --- [nio-3888-exec-1] o.s.web.servlet.DispatcherServlet        : Could not complete request
o.s.web.servlet.DispatcherServlet: Could not complete request
java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:255) ~[weixin-java-common-3.3.0.jar:na]
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:230) ~[weixin-java-common-3.3.0.jar:na]
	at me.chanjar.weixin.open.bean.message.WxOpenXmlMessage.fromEncryptedXml(WxOpenXmlMessage.java:88) ~[weixin-java-open-3.3.0.jar:na]
	at com.github.binarywang.demo.wx.open.controller.WechatNotifyController.receiveTicket(WechatNotifyController.java:41) ~[classes/:na]

```

**Comment by briefguo** [comment]
https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

难道我要这样操作？你们也要下个文件到指定目录？

**Comment by binarywang** [comment]
建议看下wiki常见问题，确实如此

**Comment by briefguo** [comment]
了解了，还是感谢🙏
